### PR TITLE
trivial: fix typos in manual

### PR DESCRIPTION
**Pull request by canarysnort01**

### CODE REVIEW

**Comment by kent-mcleod** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by kent-mcleod** [comment]
Thanks a lot!

**Pull request merged**
