### PR TITLE
manual: Document initial thread's SMMU caps

### PR DESCRIPTION
**Pull request by canarysnort01**
**Purpose**: Ready to merge.
**Testing Performed**: Visually inspected manual.

Signed-off-by: Jimmy Brush <code@jimmah.com>

### CODE REVIEW

**Comment by walle-whale** [comment]
@ssrg-bamboo `test`

**Comment by walle-whale** [comment]
Thanks~!

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
