### PR TITLE
Switch to pragma once include guards

### PR DESCRIPTION
**Pull request by axel-h**
Follow up on the work of https://github.com/seL4/seL4/pull/281
* Switch to pragma once include guards

### CODE REVIEW

**Review by kent-mcleod — APPROVED** [review]
Nice

**Review by bennoleslie — APPROVED** [review]
This looks good to me. I don't see any possible negative impact, and this makes it more consistent with the use of `#pragma once` in other places.

But I'm not an expert, someone else should also review and approve.

**Comment by axel-h** [comment]
could you merge this also now? I've removed the commit that removed removed AUTOCONF_INCLUDED, because I'll wait with this after https://github.com/seL4/seL4/pull/300 got merged

**Comment by oliver-wm** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
