### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by axel-h**
* seems nobody is using `AUTOCONF_INCLUDED`, so I'm removing this now to get rid of some legacy.
* the "pragma once" include guard is a bit more elegant

### CODE REVIEW

**Comment by axel-h** [comment]
Seems https://sel4.systems/Info/Docs/seL4-manual-latest.pdf is no longer working, did this change recently?

**Comment by lsf37** [comment]
> The automated check for links fails because of #371

They are back, the checks now pass again.

**Comment by pingerino** [comment]
We use guard once to check this in style.sh, but this must be disabled for the kernel? https://github.com/seL4/seL4_tools/blob/master/misc/style-c.sh

**Review by kent-mcleod — COMMENTED** [review]
> seems nobody is using AUTOCONF_INCLUDED, so I'm removing this now to get rid of some legacy.

Technically I think this is a breaking API change

**Comment by axel-h** [comment]
> Technically I think this is a breaking API change

I've added a note in the `CHANGES` file

**Review by oliver-wm — APPROVED** [review]

**Comment by axel-h** [comment]
Please merge this if it passes the CI tests.

**Comment by axel-h** [comment]
@ssrg-bamboo test

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit e624f30bce55d2d402fda7f9a5a0dc89bc62979d

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - C Parser - EXT-axel-h-patch-axel-4-370 | SUCCESSFUL |
| Code Quality - Check licenses - seL4 - EXT-axel-h-patch-axel-4-370 | SUCCESSFUL |
| Code Quality - Reuse License Check - seL4 - EXT-axel-h-patch-axel-4-370 | SUCCESSFUL |
| Code Quality - Signed-off-by - seL4 - EXT-axel-h-patch-axel-4-370 | SUCCESSFUL |
| Code Quality - Style - seL4 - EXT-axel-h-patch-axel-4-370 | FAILED |
| Dev seL4 tests - seL4 PRs: Kernel Compile - EXT-axel-h-patch-axel-4-370 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Preprocess - EXT-axel-h-patch-axel-4-370 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-axel-h-patch-axel-4-370 | SUCCESSFUL |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - seL4 - EXT-axel-h-patch-axel-4-370 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    05-Jun-2021 23:19:12	Build Code Quality - Style - seL4 - EXT-axel-h-patch-axel-4-370 - style #1 (CQ-SEL4STYLE483-SEL4STYLEPR-1) started building on agent A local agent 2, bamboo version: 7.1.4
    05-Jun-2021 23:19:12	I run on the Bamboo server!
    05-Jun-2021 23:19:12	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4STYLE483-SEL4STYLEPR
    05-Jun-2021 23:19:12	Executing build Code Quality - Style - seL4 - EXT-axel-h-patch-axel-4-370 - style #1 (CQ-SEL4STYLE483-SEL4STYLEPR-1)
    05-Jun-2021 23:19:12	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4STYLE483-SEL4STYLEPR/. (location: .)
    05-Jun-2021 23:19:12	Artifact 'code' prepared in 14.86 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4STYLE483-SEL4STYLEPR/./code.tar.gz
    05-Jun-2021 23:19:12	Running pre-build action: VCS Version Collector
    05-Jun-2021 23:19:12	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Jun-2021 23:19:12	+ tar xf code.tar.gz --recursive-unlink
    05-Jun-2021 23:19:12	Finished task 'Untar code' with result: Success
    05-Jun-2021 23:19:12	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Jun-2021 23:19:12	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4STYLE483-SEL4STYLEPR
    05-Jun-2021 23:19:12	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    05-Jun-2021 23:19:12	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Jun-2021 23:19:12	+ cd seL4
    05-Jun-2021 23:19:12	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4STYLE483-SEL4STYLEPR/standard_seL4_tools/misc/style.sh
    05-Jun-2021 23:19:12	++ git merge-base e624f30bce55d2d402fda7f9a5a0dc89bc62979d db7bb413146f2a302579ff796507c059e25d22b1
    05-Jun-2021 23:19:12	+ git diff --name-only e624f30bce55d2d402fda7f9a5a0dc89bc62979d db7bb413146f2a302579ff796507c059e25d22b1
    05-Jun-2021 23:19:12	style-cmake.sh: fatal error: need version 0.4.5 of cmake-format; Traceback (most recent call last):
    05-Jun-2021 23:19:12	  File "/usr/local/bin/cmake-format", line 33, in <module>
    05-Jun-2021 23:19:12	    sys.exit(load_entry_point('cmake-format==0.4.5', 'console_scripts', 'cmake-format')())
    05-Jun-2021 23:19:12	  File "/usr/local/bin/cmake-format", line 22, in importlib_load_entry_point
    05-Jun-2021 23:19:12	    for entry_point in distribution(dist_name).entry_points
    05-Jun-2021 23:19:12	  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    05-Jun-2021 23:19:12	    return Distribution.from_name(distribution_name)
    05-Jun-2021 23:19:12	  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    05-Jun-2021 23:19:12	    raise PackageNotFoundError(name)
    05-Jun-2021 23:19:12	importlib.metadata.PackageNotFoundError: cmake-format is installed
    05-Jun-2021 23:19:12	CRITICAL:root:['tools/helpers.cmake'] failed with error code 2
    05-Jun-2021 23:19:12	b''
    05-Jun-2021 23:19:12	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4STYLE483-SEL4STYLEPR-1-ScriptBuildTask-6755977077302591455.sh] was 123 while expected 0
    05-Jun-2021 23:19:12	Finished task 'Check style of changed files' with result: Failed
    05-Jun-2021 23:19:12	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Jun-2021 23:19:12	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4STYLE483-SEL4STYLEPR
    05-Jun-2021 23:19:12	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    05-Jun-2021 23:19:12	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    05-Jun-2021 23:19:12	+ cd seL4
    05-Jun-2021 23:19:12	++ echo ssh://git@bitbucket.ts.data61.csiro.au:7999/sel4/sel4.git
    05-Jun-2021 23:19:12	++ cut -d/ -f4
    05-Jun-2021 23:19:12	+ bb_proj=sel4
    05-Jun-2021 23:19:12	+ /scripts/bb_code_insights/create_code_insights.sh astyle sel4 seL4
    05-Jun-2021 23:19:12	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    05-Jun-2021 23:19:12	+ SCRIPT_DIR=/scripts/bb_code_insights
    05-Jun-2021 23:19:12	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    05-Jun-2021 23:19:12	+ BBS_PROJECT=sel4
    05-Jun-2021 23:19:12	+ BBS_REPO=seL4
    05-Jun-2021 23:19:12	+ REPORT_TO_RUN=astyle
    05-Jun-2021 23:19:12	++ git rev-parse HEAD
    05-Jun-2021 23:19:12	+ COMMIT_ID=e624f30bce55d2d402fda7f9a5a0dc89bc62979d
    05-Jun-2021 23:19:12	+ REPORT_KEY=astyle.report
    05-Jun-2021 23:19:12	+ set +x
    05-Jun-2021 23:19:12	+ report_file=astyle_report.json
    05-Jun-2021 23:19:12	+ annotations_file=astyle_annotations.json
    05-Jun-2021 23:19:12	+ rm -f astyle_report.json astyle_annotations.json
    05-Jun-2021 23:19:12	+ /scripts/bb_code_insights/astyle
    05-Jun-2021 23:19:12	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    05-Jun-2021 23:19:12	+ set +x
    05-Jun-2021 23:19:12	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    05-Jun-2021 23:19:12	+ '[' -f astyle_report.json ']'
    05-Jun-2021 23:19:12	+ cat astyle_report.json
    05-Jun-2021 23:19:12	{"data":[{"title":"Total number of files with incorrect style","value":0},{"title":"Total number of lines with incorrect style","value":0}],"createdDate":1622899153868,"key":"astyle.report","title":"Code style"}{"title": "Code style", "data": [{"title": "Total number of files with incorrect style", "value": 0}, {"title": "Total number of lines with incorrect style", "value": 0}]}
    05-Jun-2021 23:19:12	+ '[' -f astyle_annotations.json ']'
    05-Jun-2021 23:19:12	Finished task 'Run astyle code insights' with result: Success
    05-Jun-2021 23:19:12	Running post build plugin 'NCover Results Collector'
    05-Jun-2021 23:19:12	Running post build plugin 'Artifact Copier'
    05-Jun-2021 23:19:12	Running post build plugin 'npm Cache Cleanup'
    05-Jun-2021 23:19:12	Running post build plugin 'Clover Results Collector'
    05-Jun-2021 23:19:12	Running post build plugin 'Docker Container Cleanup'
    05-Jun-2021 23:19:13	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-SEL4STYLE483-SEL4STYLEPR'
    05-Jun-2021 23:19:13	Finalising the build...
    05-Jun-2021 23:19:13	Stopping timer.
    05-Jun-2021 23:19:13	Build CQ-SEL4STYLE483-SEL4STYLEPR-1 completed.
    05-Jun-2021 23:19:13	Running on server: post build plugin 'NCover Results Collector'
    05-Jun-2021 23:19:13	Running on server: post build plugin 'Build Hanging Detection Configuration'
    05-Jun-2021 23:19:13	Running on server: post build plugin 'Clover Delta Calculator'
    05-Jun-2021 23:19:13	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    05-Jun-2021 23:19:13	All post build plugins have finished
    05-Jun-2021 23:19:13	Generating build results summary...
    05-Jun-2021 23:19:13	Saving build results to disk...
    05-Jun-2021 23:19:13	Store variable context...
    05-Jun-2021 23:19:13	Indexing build results...
    05-Jun-2021 23:19:13	Finished building CQ-SEL4STYLE483-SEL4STYLEPR-1.


This is the most I can report on right now, sorry!

**Comment by axel-h** [comment]
The failure `style-cmake.sh: fatal error: need version 0.4.5 of cmake-format` seems unrelated.

**Review by kent-mcleod — APPROVED** [review]

**Pull request merged**
