### PR TITLE
Fix x86 interrupt 21 macro definition, vcpu_finalise error condition, typos

### PR DESCRIPTION
**Pull request by laokz**
This might be copied from precedent & forgotten updating its name:)

### CODE REVIEW

**Comment by laokz** [comment]
By the way, I want to sign CLA through https://cla-assistant.io/. I do config and link it to my forked seL4. But I don't know whether I succeeded the assignment. If not, please let me know and best giving any instructors.

**Comment by laokz** [comment]
Sorry if these look chaos, i m not familiar with PRs. And pls tell me if needed to retry.

thks.

**Comment by laokz** [comment]
I ran the newest sel4test with my forked and committed kernel. The result is:
```
Starting test 122: Test all tests ran
Test suite passed. 122 tests passed. 54 tests disabled.
All is well in the universe
```
Wish this info useful.

**Comment by yyshen** [comment]
@laokz Would you be able to rebase the commits with master and commit with "-s" option to add the "Sign-off by"?

**Comment by laokz** [comment]
Ahh bad, I failed to add '-s' within the web. And these commits looks mess, I agree that we can treat them as issues instead.

**Comment by yyshen** [comment]
> Ahh bad, I failed to add '-s' within the web. And these commits looks mess, I agree that we can treat them as issues instead.

@laokz Do you mind if we fix the issues based on your feedback, with new commits. @kent-mcleod @lsf37 is there a way to acknowledge his contribution in the new commits?

**Comment by lsf37** [comment]
Yes, we can reference back to this pull request in the new PR and commit message, and we can also add a line

`Co-authored-by: laokz <laokz@foxmail.com>` 

to the commit message, which should cause github to pick up the correct author.

**Comment by lsf37** [comment]
The preprocess change for x64 is most likely fine. If it does break the proof it should be trivial to change. If/when you have a new PR, let me know and I'll run a full proof test for it.

**Comment by laokz** [comment]
> @laokz Do you mind if we fix the issues based on your feedback, with new commits.  @kent-mcleod @lsf37 is there a way to acknowledge his contribution in the new commits?

Sure, my pleasure, and your reply already acknowledged me.

**Comment by yyshen** [comment]
@laokz @lsf37  A new PR #212 is created based on this PR.

**Comment by yyshen** [comment]
The proposed changes have been merged in PR #212. @laokz, thank you for the contribution.

**Pull request closed without merging**
