### PR TITLE
machine/statedata: align idle thread

### PR DESCRIPTION
**Pull request by yf13**
The `TCB_PTR_CTE_PTR()` macro assumes that thread block aligns with `bit(seL4_TCBBits)`. However this is not true for the idle thread block, thus using the macro with idle thread leads to invalid results. This fixes the issue by apply same alignment to idle thread block so that the macro applies to all threads.

### CODE REVIEW

**Comment by Indanz** [comment]
`TCB_PTR_CTE_PTR` should never be used on the idle thread, how did you ran into this issue?

**Comment by lsf37** [comment]
> `TCB_PTR_CTE_PTR` should never be used on the idle thread, how did you ran into this issue?

I don't think we have explicitly proved this, but I agree, the macro should never be applied to the idle thread. If that happens we have bigger problems.

Having said that, the verification does have the blanket assumption on the initial state that all TCBs are aligned the same way and the idle thread TCB is still a TCB, so I would actually vote for making this change for that reason even though there should be no correctness issue -- if we verify kernel init at some point, we're going to need it to establish that assumption.

**Comment by lsf37** [comment]
I would ask to update the commit message, though, to something along these lines:

```
Change the alignment of the idle thread to be consistent with standard
TCBs. Even though macros like TCB_PTR_CTE_PTR should not be used
on the idle thread, verification assumes consistent alignment for all TCBs.
```

**Comment by yf13** [comment]
The `setThreadName()` uses `TCB_PTR_DEBUG_PTR` which uses `TCB_PTE_CTE_PTR`. Idle thread has name set with debug build.

**Comment by lsf37** [comment]
> The `setThreadName()` uses `TCB_PTR_DEBUG_PTR` which uses `TCB_PTE_CTE_PTR`. Idle thread has name set with debug build.

Well, that's indeed bad. I'm definitely in favour of merging this then. Verification would not pick up on debug mode uses, so nice job spotting this.

I wonder why this has not led to problems so far. It's possible that the linker is picking a larger alignment for the idle thread section anyway and that has saved things. Otherwise setting the thread name would have been corrupting other state at boot time already.

**Review by lsf37 — APPROVED** [review]

**Pull request merged**
