### PR TITLE
boot: make linker definitions generic

### PR DESCRIPTION
**Pull request by axel-h**

### CODE REVIEW

**Review by pingerino — APPROVED** [review]

**Comment by lsf37** [comment]
Looks fine from the verification side, but I'll start a proof testboard to make sure:

@ssrg-bamboo `proof`

**Review by lsf37 — APPROVED** [review]
Happy for you to merge when the proofs come back positive.

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I've set up a proof testboard for this PR [here](https://github.com/seL4/gh-testboard/blob/axel-h-patch-axel-16-420-221135/manifest.xml), and results should show up as `pending` in status checks in a few minutes.

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I've set up a proof testboard for this PR [here](https://github.com/seL4/gh-testboard/blob/axel-h-patch-axel-16-420-221205/manifest.xml), and results should show up as `pending` in status checks in a few minutes.

**Comment by kent-mcleod** [comment]
> Happy for you to merge when the proofs come back positive.

`build	29-Jun-2021 00:52:04	*** exception Fail raised (line 171 of "/home/bamboo/bamboo-agent-home/xml-data/build-dir/L4V-GHTESTBOARD59-ARMVERIFY/l4v/tools/c-parser/calculate_state.ML"): translate_inttype: incomplete array!`

**Comment by axel-h** [comment]
What does this error mean?
```
build 29-Jun-2021 00:52:04 *** exception Fail raised (line 171 of "/home/bamboo/bamboo-agent-home/xml-data/build-dir/L4V-GHTESTBOARD59-ARMVERIFY/l4v/tools/c-parser/calculate_state.ML"): translate_inttype: incomplete array!
```

**Comment by lsf37** [comment]
> What does this error mean?
> 
> ```
> build 29-Jun-2021 00:52:04 *** exception Fail raised (line 171 of "/home/bamboo/bamboo-agent-home/xml-data/build-dir/L4V-GHTESTBOARD59-ARMVERIFY/l4v/tools/c-parser/calculate_state.ML"): translate_inttype: incomplete array!
> ```

```c
extern char ki_boot_end[];
```

It looks like the parser is trying to compute the size of this array and is failing. I don't think it supports arrays of unknown length for global variables. You could make it a pointer, though.

**Comment by lsf37** [comment]
> > What does this error mean?
> > ```
> > build 29-Jun-2021 00:52:04 *** exception Fail raised (line 171 of "/home/bamboo/bamboo-agent-home/xml-data/build-dir/L4V-GHTESTBOARD59-ARMVERIFY/l4v/tools/c-parser/calculate_state.ML"): translate_inttype: incomplete array!
> > ```
> 
> ```c
> extern char ki_boot_end[];
> ```
> 
> It looks like the parser is trying to compute the size of this array and is failing. I don't think it supports arrays of unknown length for global variables. You could make it a pointer, though.

Or not, because `ki_end[]` is already there and seems fine. Let me look at this in more detail

**Comment by mbrcknl** [comment]
> > It looks like the parser is trying to compute the size of this array and is failing. I don't think it supports arrays of unknown length for global variables. You could make it a pointer, though.
> 
> Or not, because `ki_end[]` is already there and seems fine. Let me look at this in more detail

I wonder if `ki_end[]` was previously only ok because the concatenated source also included  `ki_end[1]`. Maybe the C parser is only reporting the first problem it finds, and for some reason it comes across `ki_boot_end[]` before `ki_endp[]`.

Indeed the fact that we previously had `ki_end[1]` suggests to me that your first guess was correct.

**Comment by lsf37** [comment]
The standalone-parser succeeded, so this really must be in the semantic part where it tries to compute the size. Would it be problematic to change the line to `ki_boot_end[1]` or do we expect any other sizes than `1`?

**Comment by mbrcknl** [comment]
> The standalone-parser succeeded, so this really must be in the semantic part where it tries to compute the size. Would it be problematic to change the line to `ki_boot_end[1]` or do we expect any other sizes than `1`?

Had a quick look at the C parser, and yes, the size is needed to determine the types to be declared in Isabelle. That calculation is done in the main C parser, but not the standalone parser. Incomplete extern array declarations are ok, as long as there is *also* a sized one. (That's how `ki_end[]` previously survived.)

**Comment by axel-h** [comment]
I've changed this not to a fixed array length 1. My guess why this was made an array and not just "plain" integer variable is, that for an array it's implicitly a pointer when using the variable's name in an expression, while for a integer variable the explicit `&` is needed.

**Comment by lsf37** [comment]
Cool, I agree. Let's try the proofs again: @ssrg-bamboo `proof`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I've set up a proof testboard for this PR [here](https://github.com/seL4/gh-testboard/blob/axel-h-patch-axel-16-420-091742/manifest.xml), and results should show up as `pending` in status checks in a few minutes.

**Comment by kent-mcleod** [comment]
Proofs passed on this commit: https://github.com/seL4/seL4/commit/1aba0be72cfba8908bb81ea4873d6670e43b9bb7

**Comment by kent-mcleod** [comment]
Merged and bumped

**Pull request merged**
