### PR TITLE
trivial: improve cmake file readability

### PR DESCRIPTION
**Pull request by axel-h**
Signed-off-by: Axel Heider <axelheider@gmx.de>

### CODE REVIEW

**Comment by kent-mcleod** [comment]
@axel-h, unfortunately I believe that the CMake formatter we use won't accept these changes: @ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 7512fb114b0f3a0fa2299ccacdc4b93582f1f819

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - C Parser - EXT-axel-h-patch-axel-4-197 | SUCCESSFUL |
| Code Quality - Check licenses - seL4 - EXT-axel-h-patch-axel-4-197 | SUCCESSFUL |
| Code Quality - Signed-off-by - seL4 - EXT-axel-h-patch-axel-4-197 | SUCCESSFUL |
| Code Quality - Style - seL4 - EXT-axel-h-patch-axel-4-197 | FAILED |
| Dev seL4 tests - seL4 PRs: Kernel Compile - EXT-axel-h-patch-axel-4-197 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Preprocess - EXT-axel-h-patch-axel-4-197 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-axel-h-patch-axel-4-197 | SUCCESSFUL |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - seL4 - EXT-axel-h-patch-axel-4-197 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    04-May-2020 11:18:11	Build Code Quality - Style - seL4 - EXT-axel-h-patch-axel-4-197 - style #1 (CQ-SEL4STYLE311-SEL4STYLEPR-1) started building on agent A local agent 1
    04-May-2020 11:18:11	I run on the Bamboo server!
    04-May-2020 11:18:11	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR
    04-May-2020 11:18:11	Executing build Code Quality - Style - seL4 - EXT-axel-h-patch-axel-4-197 - style #1 (CQ-SEL4STYLE311-SEL4STYLEPR-1)
    04-May-2020 11:18:11	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR/. (location: .)
    04-May-2020 11:18:11	Artifact 'code' prepared in 24.83 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR/./code.tar.gz
    04-May-2020 11:18:11	Running pre-build action: VCS Version Collector
    04-May-2020 11:18:11	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-May-2020 11:18:11	+ tar xf code.tar.gz --recursive-unlink
    04-May-2020 11:18:11	Finished task 'Untar code' with result: Success
    04-May-2020 11:18:11	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-May-2020 11:18:11	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR
    04-May-2020 11:18:11	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    04-May-2020 11:18:11	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-May-2020 11:18:11	+ cd seL4
    04-May-2020 11:18:11	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR/seL4_tools/misc/style.sh
    04-May-2020 11:18:11	++ git merge-base 7512fb114b0f3a0fa2299ccacdc4b93582f1f819 d7c35bf6a31b64051763436edc9dd744ecaf129d
    04-May-2020 11:18:11	+ git diff --name-only 7512fb114b0f3a0fa2299ccacdc4b93582f1f819 d7c35bf6a31b64051763436edc9dd744ecaf129d
    04-May-2020 11:18:13	+ git diff --exit-code
    04-May-2020 11:18:13	diff --git a/src/drivers/serial/config.cmake b/src/drivers/serial/config.cmake
    04-May-2020 11:18:13	index c93a8c917..fa8661371 100644
    04-May-2020 11:18:13	--- a/src/drivers/serial/config.cmake
    04-May-2020 11:18:13	+++ b/src/drivers/serial/config.cmake
    04-May-2020 11:18:13	@@ -12,11 +12,7 @@ register_driver(
    04-May-2020 11:18:13	     CFILES "bcm2835-aux-uart.c"
    04-May-2020 11:18:13	 )
    04-May-2020 11:18:13	 
    04-May-2020 11:18:13	-register_driver(
    04-May-2020 11:18:13	-    compatibility_strings "arm,pl011"
    04-May-2020 11:18:13	-    PREFIX src/drivers/serial
    04-May-2020 11:18:13	-    CFILES "pl011.c"
    04-May-2020 11:18:13	-)
    04-May-2020 11:18:13	+register_driver(compatibility_strings "arm,pl011" PREFIX src/drivers/serial CFILES "pl011.c")
    04-May-2020 11:18:13	 
    04-May-2020 11:18:13	 register_driver(
    04-May-2020 11:18:13	     compatibility_strings "nvidia,tegra20-uart;ti,omap3-uart;snps,dw-apb-uart"
    04-May-2020 11:18:13	@@ -42,11 +38,7 @@ register_driver(
    04-May-2020 11:18:13	     CFILES "msm-uartdm.c"
    04-May-2020 11:18:13	 )
    04-May-2020 11:18:13	 
    04-May-2020 11:18:13	-register_driver(
    04-May-2020 11:18:13	-    compatibility_strings "xlnx,xuartps"
    04-May-2020 11:18:13	-    PREFIX src/drivers/serial
    04-May-2020 11:18:13	-    CFILES "xuartps.c"
    04-May-2020 11:18:13	-)
    04-May-2020 11:18:13	+register_driver(compatibility_strings "xlnx,xuartps" PREFIX src/drivers/serial CFILES "xuartps.c")
    04-May-2020 11:18:13	 
    04-May-2020 11:18:13	 register_driver(
    04-May-2020 11:18:13	     compatibility_strings "amlogic,meson-gx-uart"
    04-May-2020 11:18:13	diff --git a/src/drivers/timer/config.cmake b/src/drivers/timer/config.cmake
    04-May-2020 11:18:13	index fba7d9a0a..7065e27be 100644
    04-May-2020 11:18:13	--- a/src/drivers/timer/config.cmake
    04-May-2020 11:18:13	+++ b/src/drivers/timer/config.cmake
    04-May-2020 11:18:13	@@ -36,11 +36,7 @@ register_driver(
    04-May-2020 11:18:13	     CFILES "imx31-epit.c"
    04-May-2020 11:18:13	 )
    04-May-2020 11:18:13	 
    04-May-2020 11:18:13	-register_driver(
    04-May-2020 11:18:13	-    compatibility_strings "fsl,imx31-gpt"
    04-May-2020 11:18:13	-    PREFIX src/drivers/timer
    04-May-2020 11:18:13	-    CFILES "imx31-gpt.c"
    04-May-2020 11:18:13	-)
    04-May-2020 11:18:13	+register_driver(compatibility_strings "fsl,imx31-gpt" PREFIX src/drivers/timer CFILES "imx31-gpt.c")
    04-May-2020 11:18:13	 
    04-May-2020 11:18:13	 register_driver(
    04-May-2020 11:18:13	     compatibility_strings "ti,omap3430-timer"
    04-May-2020 11:18:13	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4STYLE311-SEL4STYLEPR-1-ScriptBuildTask-3573192033931088566.sh] was 1 while expected 0
    04-May-2020 11:18:13	Finished task 'Check style of changed files' with result: Failed
    04-May-2020 11:18:13	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-May-2020 11:18:13	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR
    04-May-2020 11:18:13	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    04-May-2020 11:18:13	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    04-May-2020 11:18:13	+ cd seL4
    04-May-2020 11:18:13	++ echo ssh://git@bitbucket.ts.data61.csiro.au:7999/sel4/sel4.git
    04-May-2020 11:18:13	++ cut -d/ -f4
    04-May-2020 11:18:13	+ bb_proj=sel4
    04-May-2020 11:18:13	+ /scripts/bb_code_insights/create_code_insights.sh astyle sel4 seL4
    04-May-2020 11:18:13	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    04-May-2020 11:18:13	+ SCRIPT_DIR=/scripts/bb_code_insights
    04-May-2020 11:18:13	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    04-May-2020 11:18:13	+ BBS_PROJECT=sel4
    04-May-2020 11:18:13	+ BBS_REPO=seL4
    04-May-2020 11:18:13	+ REPORT_TO_RUN=astyle
    04-May-2020 11:18:13	++ git rev-parse HEAD
    04-May-2020 11:18:13	+ COMMIT_ID=7512fb114b0f3a0fa2299ccacdc4b93582f1f819
    04-May-2020 11:18:13	+ REPORT_KEY=astyle.report
    04-May-2020 11:18:13	+ set +x
    04-May-2020 11:18:13	+ report_file=astyle_report.json
    04-May-2020 11:18:13	+ annotations_file=astyle_annotations.json
    04-May-2020 11:18:13	+ rm -f astyle_report.json astyle_annotations.json
    04-May-2020 11:18:13	+ /scripts/bb_code_insights/astyle
    04-May-2020 11:18:15	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    04-May-2020 11:18:15	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    04-May-2020 11:18:15	+ set +x
    04-May-2020 11:18:15	+ '[' -f astyle_report.json ']'
    04-May-2020 11:18:15	+ cat astyle_report.json
    04-May-2020 11:18:15	+ '[' -f astyle_annotations.json ']'
    04-May-2020 11:18:15	{"data":[{"title":"Total number of files with incorrect style","value":0},{"title":"Total number of lines with incorrect style","value":0}],"createdDate":1588555095825,"key":"astyle.report","title":"Code style"}{"title": "Code style", "data": [{"title": "Total number of files with incorrect style", "value": 0}, {"title": "Total number of lines with incorrect style", "value": 0}]}
    04-May-2020 11:18:15	Finished task 'Run astyle code insights' with result: Success
    04-May-2020 11:18:15	Running post build plugin 'NCover Results Collector'
    04-May-2020 11:18:15	Running post build plugin 'Artifact Copier'
    04-May-2020 11:18:15	Running post build plugin 'npm Cache Cleanup'
    04-May-2020 11:18:15	Running post build plugin 'Clover Results Collector'
    04-May-2020 11:18:15	Running post build plugin 'Docker Container Cleanup'
    04-May-2020 11:18:15	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR'
    04-May-2020 11:18:15	Finalising the build...
    04-May-2020 11:18:15	Stopping timer.
    04-May-2020 11:18:15	Build CQ-SEL4STYLE311-SEL4STYLEPR-1 completed.
    04-May-2020 11:18:15	Running on server: post build plugin 'NCover Results Collector'
    04-May-2020 11:18:15	Running on server: post build plugin 'Build Hanging Detection Configuration'
    04-May-2020 11:18:15	Running on server: post build plugin 'Clover Delta Calculator'
    04-May-2020 11:18:15	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    04-May-2020 11:18:15	All post build plugins have finished
    04-May-2020 11:18:15	Generating build results summary...
    04-May-2020 11:18:16	Saving build results to disk...
    04-May-2020 11:18:16	Store variable context...
    04-May-2020 11:18:16	Indexing build results...
    04-May-2020 11:18:16	Finished building CQ-SEL4STYLE311-SEL4STYLEPR-1.


This is the most I can report on right now, sorry!

**Comment by axel-h** [comment]
Indeed, it's complaining there. Any clue why it does this? Feels odd that it insists to put things into one line.

**Comment by hyhugh** [comment]
> Indeed, it's complaining there. Any clue why it does this? Feels odd that it insists to put things into one line.

https://github.com/seL4/seL4_tools/blob/master/misc/style-cmake.sh
please check the cmake formatting script here

**Comment by kent-mcleod** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit dd0a6f699eca9ec62ce0c65d184a2f4ac26cd693

### Summary

#### NOTE: some test results have been updated!

| Test name | Result |
| --- | --- |
| Code Quality - C Parser - EXT-axel-h-patch-axel-4-197 | SUCCESSFUL |
| Code Quality - Check licenses - seL4 - EXT-axel-h-patch-axel-4-197 | SUCCESSFUL |
| Code Quality - Signed-off-by - seL4 - EXT-axel-h-patch-axel-4-197 | SUCCESSFUL |
| Code Quality - Style - seL4 - EXT-axel-h-patch-axel-4-197 | FAILED |
| Dev seL4 tests - seL4 PRs: Kernel Compile - EXT-axel-h-patch-axel-4-197 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Preprocess - EXT-axel-h-patch-axel-4-197 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-axel-h-patch-axel-4-197 | SUCCESSFUL |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - seL4 - EXT-axel-h-patch-axel-4-197 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    11-May-2020 12:13:53	Build Code Quality - Style - seL4 - EXT-axel-h-patch-axel-4-197 - style #2 (CQ-SEL4STYLE311-SEL4STYLEPR-2) started building on agent A local agent 1
    11-May-2020 12:13:53	I run on the Bamboo server!
    11-May-2020 12:13:53	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR
    11-May-2020 12:13:53	Executing build Code Quality - Style - seL4 - EXT-axel-h-patch-axel-4-197 - style #2 (CQ-SEL4STYLE311-SEL4STYLEPR-2)
    11-May-2020 12:13:53	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR/. (location: .)
    11-May-2020 12:13:53	Artifact 'code' prepared in 31.15 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR/./code.tar.gz
    11-May-2020 12:13:53	Running pre-build action: VCS Version Collector
    11-May-2020 12:13:53	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    11-May-2020 12:13:53	+ tar xf code.tar.gz --recursive-unlink
    11-May-2020 12:13:54	Finished task 'Untar code' with result: Success
    11-May-2020 12:13:54	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    11-May-2020 12:13:54	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR
    11-May-2020 12:13:54	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    11-May-2020 12:13:54	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    11-May-2020 12:13:54	+ cd seL4
    11-May-2020 12:13:54	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR/seL4_tools/misc/style.sh
    11-May-2020 12:13:54	++ git merge-base dd0a6f699eca9ec62ce0c65d184a2f4ac26cd693 13d1a9963b8a1e135c0dad7b2020851797e8e34f
    11-May-2020 12:13:54	+ git diff --name-only dd0a6f699eca9ec62ce0c65d184a2f4ac26cd693 d5d54a0d5596e7a708a55040b58a1bb286dc9545
    11-May-2020 12:13:55	+ git diff --exit-code
    11-May-2020 12:13:55	diff --git a/src/drivers/serial/config.cmake b/src/drivers/serial/config.cmake
    11-May-2020 12:13:55	index c93a8c917..fa8661371 100644
    11-May-2020 12:13:55	--- a/src/drivers/serial/config.cmake
    11-May-2020 12:13:55	+++ b/src/drivers/serial/config.cmake
    11-May-2020 12:13:55	@@ -12,11 +12,7 @@ register_driver(
    11-May-2020 12:13:55	     CFILES "bcm2835-aux-uart.c"
    11-May-2020 12:13:55	 )
    11-May-2020 12:13:55	 
    11-May-2020 12:13:55	-register_driver(
    11-May-2020 12:13:55	-    compatibility_strings "arm,pl011"
    11-May-2020 12:13:55	-    PREFIX src/drivers/serial
    11-May-2020 12:13:55	-    CFILES "pl011.c"
    11-May-2020 12:13:55	-)
    11-May-2020 12:13:55	+register_driver(compatibility_strings "arm,pl011" PREFIX src/drivers/serial CFILES "pl011.c")
    11-May-2020 12:13:55	 
    11-May-2020 12:13:55	 register_driver(
    11-May-2020 12:13:55	     compatibility_strings "nvidia,tegra20-uart;ti,omap3-uart;snps,dw-apb-uart"
    11-May-2020 12:13:55	@@ -42,11 +38,7 @@ register_driver(
    11-May-2020 12:13:55	     CFILES "msm-uartdm.c"
    11-May-2020 12:13:55	 )
    11-May-2020 12:13:55	 
    11-May-2020 12:13:55	-register_driver(
    11-May-2020 12:13:55	-    compatibility_strings "xlnx,xuartps"
    11-May-2020 12:13:55	-    PREFIX src/drivers/serial
    11-May-2020 12:13:55	-    CFILES "xuartps.c"
    11-May-2020 12:13:55	-)
    11-May-2020 12:13:55	+register_driver(compatibility_strings "xlnx,xuartps" PREFIX src/drivers/serial CFILES "xuartps.c")
    11-May-2020 12:13:55	 
    11-May-2020 12:13:55	 register_driver(
    11-May-2020 12:13:55	     compatibility_strings "amlogic,meson-gx-uart"
    11-May-2020 12:13:55	diff --git a/src/drivers/timer/config.cmake b/src/drivers/timer/config.cmake
    11-May-2020 12:13:55	index fba7d9a0a..7065e27be 100644
    11-May-2020 12:13:55	--- a/src/drivers/timer/config.cmake
    11-May-2020 12:13:55	+++ b/src/drivers/timer/config.cmake
    11-May-2020 12:13:55	@@ -36,11 +36,7 @@ register_driver(
    11-May-2020 12:13:55	     CFILES "imx31-epit.c"
    11-May-2020 12:13:55	 )
    11-May-2020 12:13:55	 
    11-May-2020 12:13:55	-register_driver(
    11-May-2020 12:13:55	-    compatibility_strings "fsl,imx31-gpt"
    11-May-2020 12:13:55	-    PREFIX src/drivers/timer
    11-May-2020 12:13:55	-    CFILES "imx31-gpt.c"
    11-May-2020 12:13:55	-)
    11-May-2020 12:13:55	+register_driver(compatibility_strings "fsl,imx31-gpt" PREFIX src/drivers/timer CFILES "imx31-gpt.c")
    11-May-2020 12:13:55	 
    11-May-2020 12:13:55	 register_driver(
    11-May-2020 12:13:55	     compatibility_strings "ti,omap3430-timer"
    11-May-2020 12:13:55	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4STYLE311-SEL4STYLEPR-2-ScriptBuildTask-4861448301798948488.sh] was 1 while expected 0
    11-May-2020 12:13:55	Finished task 'Check style of changed files' with result: Failed
    11-May-2020 12:13:55	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    11-May-2020 12:13:55	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR
    11-May-2020 12:13:55	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    11-May-2020 12:13:55	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    11-May-2020 12:13:55	+ cd seL4
    11-May-2020 12:13:55	++ echo ssh://git@bitbucket.ts.data61.csiro.au:7999/sel4/sel4.git
    11-May-2020 12:13:55	++ cut -d/ -f4
    11-May-2020 12:13:55	+ bb_proj=sel4
    11-May-2020 12:13:55	+ /scripts/bb_code_insights/create_code_insights.sh astyle sel4 seL4
    11-May-2020 12:13:55	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    11-May-2020 12:13:55	+ SCRIPT_DIR=/scripts/bb_code_insights
    11-May-2020 12:13:55	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    11-May-2020 12:13:55	+ BBS_PROJECT=sel4
    11-May-2020 12:13:55	+ BBS_REPO=seL4
    11-May-2020 12:13:55	+ REPORT_TO_RUN=astyle
    11-May-2020 12:13:55	++ git rev-parse HEAD
    11-May-2020 12:13:55	+ COMMIT_ID=dd0a6f699eca9ec62ce0c65d184a2f4ac26cd693
    11-May-2020 12:13:55	+ REPORT_KEY=astyle.report
    11-May-2020 12:13:55	+ set +x
    11-May-2020 12:13:55	+ report_file=astyle_report.json
    11-May-2020 12:13:55	+ annotations_file=astyle_annotations.json
    11-May-2020 12:13:55	+ rm -f astyle_report.json astyle_annotations.json
    11-May-2020 12:13:55	+ /scripts/bb_code_insights/astyle
    11-May-2020 12:13:58	Reporting on these files:  ['include/arch/riscv/arch/fastpath/fastpath.h', 'include/arch/riscv/arch/machine.h', 'include/arch/riscv/arch/machine/fpu.h', 'include/arch/riscv/arch/machine/hardware.h', 'include/arch/riscv/arch/machine/registerset.h', 'libsel4/sel4_arch_include/riscv64/sel4/sel4_arch/constants.h', 'src/arch/riscv/c_traps.c', 'src/arch/riscv/kernel/boot.c', 'src/arch/riscv/machine/fpu.c', 'src/arch/riscv/object/objecttype.c', 'src/arch/riscv/object/tcb.c', 'src/arch/riscv/smp/ipi.c', 'src/smp/ipi.c', 'CMakeLists.txt']
    11-May-2020 12:13:58	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    11-May-2020 12:13:58	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    11-May-2020 12:13:58	+ set +x
    11-May-2020 12:13:58	+ '[' -f astyle_report.json ']'
    11-May-2020 12:13:58	+ cat astyle_report.json
    11-May-2020 12:13:58	+ '[' -f astyle_annotations.json ']'
    11-May-2020 12:13:58	{"data":[{"title":"Total number of files with incorrect style","value":0},{"title":"Total number of lines with incorrect style","value":0}],"createdDate":1589163238704,"key":"astyle.report","title":"Code style"}{"title": "Code style", "data": [{"title": "Total number of files with incorrect style", "value": 0}, {"title": "Total number of lines with incorrect style", "value": 0}]}
    11-May-2020 12:13:58	Finished task 'Run astyle code insights' with result: Success
    11-May-2020 12:13:58	Running post build plugin 'NCover Results Collector'
    11-May-2020 12:13:58	Running post build plugin 'Artifact Copier'
    11-May-2020 12:13:58	Running post build plugin 'npm Cache Cleanup'
    11-May-2020 12:13:58	Running post build plugin 'Clover Results Collector'
    11-May-2020 12:13:58	Running post build plugin 'Docker Container Cleanup'
    11-May-2020 12:13:58	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4STYLE311-SEL4STYLEPR'
    11-May-2020 12:13:58	Finalising the build...
    11-May-2020 12:13:58	Stopping timer.
    11-May-2020 12:13:58	Build CQ-SEL4STYLE311-SEL4STYLEPR-2 completed.
    11-May-2020 12:13:58	Running on server: post build plugin 'NCover Results Collector'
    11-May-2020 12:13:58	Running on server: post build plugin 'Build Hanging Detection Configuration'
    11-May-2020 12:13:58	Running on server: post build plugin 'Clover Delta Calculator'
    11-May-2020 12:13:58	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    11-May-2020 12:13:58	All post build plugins have finished
    11-May-2020 12:13:58	Generating build results summary...
    11-May-2020 12:13:58	Saving build results to disk...
    11-May-2020 12:13:58	Store variable context...
    11-May-2020 12:13:58	Indexing build results...
    11-May-2020 12:13:58	Finished building CQ-SEL4STYLE311-SEL4STYLEPR-2.


This is the most I can report on right now, sorry!

**Comment by lsf37** [comment]
Sorry for the mismatch between the github and the bamboo test. The fix should be out with the next deployment run.

Unfortunately, bamboo was the correct one. I believe the problem is simply that `cmake-format` prefers single lines unless they have to be broken because they are too long. If you can find a config option that makes that less stupid, we'd be happy to look at that.

**Comment by axel-h** [comment]
@lsf37: thanks, I'll have a look into this. But I have to admin this is not the highest thing on the priority list ;)

**Comment by lsf37** [comment]
Fair enough :-)

**Comment by axel-h** [comment]
I'm giving up (at least for the near future) and will just comply with the formatter's opinion.

**Pull request closed without merging**
