### PR TITLE
testing: random proof-breaking change

### PR DESCRIPTION
**Pull request by lsf37**
testing only, do not merge

### CODE REVIEW

**Comment by lsf37** [comment]
@ssrg-bamboo `proof`

**Comment by lsf37** [comment]
@ssrg-bamboo `proof`

**Comment by lsf37** [comment]
and once more..
@ssrg-bamboo `proof`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I've set up a proof testboard for this PR, and results should show up as `pending` in status checks in a few minutes.

**Comment by lsf37** [comment]
@ssrg-bamboo `proof`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I've set up a proof testboard for this PR [here](https://github.com/seL4/gh-testboard/blob/verification-seL4-test-343//manifest.xml), and results should show up as `pending` in status checks in a few minutes.

**Comment by axel-h** [comment]
Cool. But I get a 404 for the link. Seems "...//manifest.xml" is missing something between the slashes?

**Comment by lsf37** [comment]
Yes, it's not working yet, still debugging :-)

Almost there, but I have a meeting now..

**Comment by lsf37** [comment]
Next iteration: @ssrg-bamboo `proof`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I've set up a proof testboard for this PR [here](https://github.com/seL4/gh-testboard/blob/seL4-test-343-103650/manifest.xml), and results should show up as `pending` in status checks in a few minutes.

**Comment by lsf37** [comment]
Still not there yet.. @ssrg-bamboo `proof`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I've set up a proof testboard for this PR [here](https://github.com/seL4/gh-testboard/blob/seL4-test-343-104754/manifest.xml), and results should show up as `pending` in status checks in a few minutes.

**Comment by lsf37** [comment]
@ssrg-bamboo `proof`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I've set up a proof testboard for this PR [here](https://github.com/seL4/gh-testboard/blob/seL4-test-343-105110/manifest.xml), and results should show up as `pending` in status checks in a few minutes.

**Comment by lsf37** [comment]
@ssrg-bamboo `proof`

**Comment by lsf37** [comment]
@ssrg-bamboo `proof`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I've set up a proof testboard for this PR [here](https://github.com/seL4/gh-testboard/blob/seL4-test-343-111233/manifest.xml), and results should show up as `pending` in status checks in a few minutes.

**Comment by lsf37** [comment]
This seems to be working now. Cautiously optimistic to use for real..

**Comment by lsf37** [comment]
@axel-h You should be able to kick off proof testboards with this command now. The bot will take a few minutes to respond, and it will take another few minutes for things to show up (and then a few hours for the proofs to finish).

**Comment by axel-h** [comment]
@lsf37 but this runs on Data61 server then, not on Github I assume. So use with great care not to exhaust things.

**Comment by lsf37** [comment]
It does, yes, and it's configured to max 4 concurrent runs -- if there are more it'll wait until one is done which can take quite a while.

**Pull request closed without merging**
