### PR TITLE
Remove deprecated libsel4 headers (address #813)

### PR DESCRIPTION
**Pull request by axel-h**
Remove deprecated libsel4 headers and cleanup the `deprecated.h` files.

Addresses https://github.com/seL4/seL4/issues/813

### CODE REVIEW

**Comment by pingerino** [comment]
Can we keep the deprecated files, even if they are empty? I'm sure we will deprecate more things in future, and it's good to have an established pattern/placeholder to put things.

**Comment by axel-h** [comment]
> Can we keep the deprecated files, even if they are empty? I'm sure we will deprecate more things in future, and it's good to have an established pattern/placeholder to put things.

I've kept the `deprecated.h` files in the arch-specific folders, as they appear to be the place where legacy/deprecation would be moved before things get dropped eventually. I have deleted the `pfIPC.h` and `exIPC.h` files, because they appear to be real legacy by now, the code contents were removed by you in 2016 already. I can see your point, that they serve as an example, but I wonder if it's better for the code base to cut off some legacy eventually to avoid bloating. I'd argue, that the code base is not so complex that this is something to keep alive, one could reference this in the history (or this PR), if the issue comes up again. Actually, I found it a bit confusing that these files exist and was wondering if I'm missing something that is still attached here.

**Comment by pingerino** [comment]
> > Can we keep the deprecated files, even if they are empty? I'm sure we will deprecate more things in future, and it's good to have an established pattern/placeholder to put things.
> 
> I've kept the `deprecated.h` files in the arch-specific folders, as they appear to be the place where legacy/deprecation would be moved before things get dropped eventually. I have deleted the `pfIPC.h` and `exIPC.h` files, because they appear to be real legacy by now, the code contents were removed by you in 2016 already. I can see your point, that they serve as an example, but I wonder if it's better for the code base to cut off some legacy eventually to avoid bloating. I'd argue, that the code base is not so complex that this is something to keep alive, one could reference this in the history (or this PR), if the issue comes up again. Actually, I found it a bit confusing that these files exist and was wondering if I'm missing something that is still attached here.

Ah, Looks like you had already done what I was thinking and my morning brain couldn't put two and two together.

Originally I kept the pfIPC etc headers because some projects used them and would break. It's probably ok to delete them now.

**Comment by axel-h** [comment]
Could this be merged?

**Review by kent-mcleod — APPROVED** [review]

**Pull request merged**
