### PR TITLE
Hardware Debug API: Single stepping on ARMv7

### PR DESCRIPTION
**Pull request by alwin-joshy**
The implementation of single-stepping on ARMv7 relies on instruction breakpoint mismatches. In the implementation, it sets one of the breakpoint value registers (BVR) to the virtual address NULL and configures the corresponding breakpoint control register to generate a debug exception whenever an instruction that does not match this address is executed. I believe this is incorrect because it means that when single-stepping is enabled, no progress will ever be made and every instruction will mismatch with NULL and result in a debug exception being generated.

I believe the correct behavior is to instead set the debug value register to be the current LR. Then, what will happen instead is that once the thread is permitted to run again, the instruction that is returned to will be executed, and the PC will then advance, resulting in a debug exception being generated before another instruction can be executed.

This PR changes the logic in the initial configuring of single stepping to set the BVR to the current LR. It also changes the handling of a single-stepping debug exception to update the BVR register to the new LR so that it works when single-stepping is configured to step over several instructions before sending a debug fault to the appropriate fault handler thread.

Test with: https://github.com/seL4/sel4test/pull/111

### CODE REVIEW

**Review by Indanz — COMMENTED** [review]
A few comments:
- Comment lines are too long, please limit to 80 characters.
- Please use `curr_thread` everywhere instead of sometimes `NODE_STATE(ksCurThread)`.
- Please add a local variable for the `curr_thread->tcbArch.tcbContext` pointer and use that.
- Remove the confusing `n_instr == 0` part of the comment, it's not relevant here.

Hard to believe it never worked and was never tested, it was introduced in 2016 by commit bebfcf6d2755d956d7c4dad499dde1527afd89c5.

**Comment by Indanz** [comment]
Do we get two traps if single-stepping over a breakpoint? If not, just checking whether single-stepping is enabled could be sufficient.

**Comment by alwin-joshy** [comment]
> A few comments:
> 
>     * Comment lines are too long, please limit to 80 characters.
> 
>     * Please use `curr_thread` everywhere instead of sometimes `NODE_STATE(ksCurThread)`.
> 
>     * Please add a local variable for the `curr_thread->tcbArch.tcbContext` pointer and use that.
> 
>     * Remove the confusing `n_instr == 0` part of the comment, it's not relevant here.
> 
> 
> Hard to believe it never worked and was never tested, it was introduced in 2016 by commit [bebfcf6](https://github.com/seL4/seL4/commit/bebfcf6d2755d956d7c4dad499dde1527afd89c5).

Agreed, it would be quite strange if it didn't work, but I tried it as is with the test I added in https://github.com/seL4/sel4test/pull/111 and it didn't work. It's possible that I'm using the API incorrectly but I don't really see how else it would be used and there were no existing single-stepping tests for ARM.

**Comment by Indanz** [comment]
> With this being the case, I don't understand how setting DBGBVR to NULL would let you simulate single stepping, as it should result in a breakpoint exception whenever the code being executed is not at vaddr NULL.

The ARM manuals says:

> Breakpoint debug events are synchronous. That is, the debug event acts like an exception that cancels the breakpointed instruction.

So I assume the code was tested to see if it triggers breakpoint events, but never actually used by anyone. I guess no one made a remote gdb debugger for seL4 yet.

**Comment by alwin-joshy** [comment]
> So I assume the code was tested to see if it triggers breakpoint events, but never actually used by anyone. I guess no one made a remote gdb debugger for seL4 yet.

That's what I'm working on at the moment, which is the reason for this sudden noise about the hardware debug api :p

**Comment by Indanz** [comment]
> > I guess no one made a remote gdb debugger for seL4 yet.
> 
> That's what I'm working on at the moment, which is the reason for this sudden noise about the hardware debug api :p

Cool. Could you make the IO part modular and write it as a library so it's easily integrated into existing systems? Then UART, IP, USB or even GPIO could be used for debugging. (Assuming you're releasing the code of course, if not, carry on.)

**Comment by alwin-joshy** [comment]
> > > I guess no one made a remote gdb debugger for seL4 yet.
> > 
> > 
> > That's what I'm working on at the moment, which is the reason for this sudden noise about the hardware debug api :p
> 
> Cool. Could you make the IO part modular and write it as a library so it's easily integrated into existing systems? Then UART, IP, USB or even GPIO could be used for debugging. (Assuming you're releasing the code of course, if not, carry on.)

The intention is to have the stub as a microkit component that can be hooked up with the sDDF for whatever interfaces you need.

**Review by Indanz — APPROVED** [review]

**Comment by alwin-joshy** [comment]
> @alwin-joshy Can you please update the commit messages to give more context what is going on? (as in the PR description) E.g. in `fix single stepping ..` explain what is being fixed, what was wrong before and it is the difference now, in `Improve ..` describe what is being improved and why, in `Update comment`, describe why (what was wrong with it).

They all just build on the first commit so I think I'll just squash them. Was just waiting till Indan was happy with the state of the PR.

**Comment by Indanz** [comment]
It looks good and passes the test, so I'm happy with it.

**Pull request merged**
