### PR TITLE
Disable KernelRiscvUseClintMtime by default

### PR DESCRIPTION
**Pull request by Ivan-Velickovic**
This configuration option requires access to the CLINT in S-mode which is not available on newer versions of OpenSBI. Because of this, it makes more sense to not turn on this option by default and instead let it be 'opt-in' for those who want the performance benefit and also have firmware that does not restrict S-mode access to the CLINT.

Closes https://github.com/seL4/seL4/issues/1094.
Closes https://github.com/seL4/seL4/issues/1258.

### CODE REVIEW

**Review by lsf37 — APPROVED** [review]
Looks good, thanks for resolving this one!

**Review by axel-h — APPROVED** [review]
Looks good

**Comment by Ivan-Velickovic** [comment]
The style check is failing on something unrelated.

**Comment by Ivan-Velickovic** [comment]
But other than that I think it’s okay to merge?

**Comment by lsf37** [comment]
> The style check is failing on something unrelated.

Yes, probably because the style checker settings have been updated a while ago, it's nothing you changed, just happens to be in a file you touched.

**Comment by Ivan-Velickovic** [comment]
I don't have access to merge a PR that has a failing 'required' check so if someone else could that would be great.

**Pull request merged**
