### PR TITLE
Fix gic_dist_map->res9 size.

### PR DESCRIPTION
**Pull request by Indanz**
Binary compatible with old code because of padding before the 64-bit iroutern field.

Without the lucky padding the offset to iroutern would be wrong.

### CODE REVIEW

**Review by axel-h — APPROVED** [review]
Change seem sane. Maybe we should add some static asserts after the definition to check that some offset are sane. Something like:
```
// check that some_field is really at offset 0x42
_Static_Assert( 0x42 == (uintptr_t)&((some_reg_struct_t *)0)->some_field );
```

**Comment by Indanz** [comment]
I added the static assert check for iroutern as that is the last field.

I also checked the other structures in that header file the same way, but those are a lot simpler, so I didn't commit those checks.

**Comment by axel-h** [comment]
Nice! Could Can you break the line at 80 chars, to improve code readability?

**Comment by axel-h** [comment]
Seems the style checker is still unhappy with the indention.

**Review by kent-mcleod — APPROVED** [review]
Nice find!

**Comment by Indanz** [comment]
I found it when reviewing #378. I didn't realise Ben didn't add that table and just checked all offsets just in case.

**Comment by lsf37** [comment]
>Something like:
> 
> ```
> // check that some_field is really at offset 0x42
> _Static_Assert( 0x42 == (uintptr_t)&((some_reg_struct_t *)0)->some_field );
> ```

For posterity: please do not use `_Static_Assert` in the kernel code, it's not C99 and not in the verification subset. Instead use `compile_assert`, which maps to `_Static_Assert` when that is available and can be handled properly by the C parser in the verification tool chain (see also #1048).

**Pull request merged**
