### PR TITLE
zynqmp: add Ultra96 platform

### PR DESCRIPTION
**Pull request by axel-h**
Add Ultra96 platform, which is based on the zynqmp SoC

### CODE REVIEW

**Comment by axel-h** [comment]
Is it ok to introduce CONFIG_PLAT_ZYNQMP_ULTRA96 or should there be only CONFIG_PLAT_ULTRA96? I've seen that for iMX6 there is just CONFIG_PLAT_SABRE and CONFIG_PLAT_WANDQ, but no CONFIG_PLAT_IMX6_WANDQ or CONFIG_PLAT_IMX6_SABRE. For iMX7/Sabre there seems to be a CONFIG_PLAT_IMX7_SABRE.

**Comment by axel-h** [comment]
I'm also wondering if `autoconf.h` should be included in `devices.h` to guarantee that `CONFIG_PLAT_ZYNQMP_ULTRA96` is defined. But looking at `include/plat/imx6/plat/machine/devices.h` it checks `CONFIG_PLAT_SABRE` also without including `autoconf.h. But this could be something to fix then, give that every file should better include the header it depends on and not expect others to do this.

**Comment by pingerino** [comment]
Hi @axel-h, our ARM platform naming conventions aren't great (and ARM devices themselves aren't helping). 

From your commits it looks like the only difference is the UART, so this is essentially the same platform with a tweak to the config. Your solution seems fine to me.

**Comment by pingerino** [comment]
also @axel-h yes, all files should include `<autoconf.h>`. Given the way the kernel builds it can easily be forgotten and everything still works.

**Pull request merged**
