### PR TITLE
aarch64 verification tweaks

### PR DESCRIPTION
**Pull request by lsf37**
- refactor/remove `getMapRefForASID` for verification convenience
- add retype annotations for AArch64
- constrain `irq_w` field width in `VPPIEvent` to maxIRQ bit width

The last of these (`irq_w` field width) might be a problem on `tqma8xqp1gb` where `maxIRQ` is 512, which means the irq bit width is 10 instead of 9 like on the other platforms. This looks like a mistake to me, though, it'd be strange if the platform had exactly 513 IRQs instead of 512 (in which case maxIRQ should be set to 511). See also #1155.

### CODE REVIEW

**Review by Indanz — APPROVED** [review]
Code seems good to me. Just add the tqma IRQ fix and it's ready to go.

I don't understand why aarch64 is using VMID as ASID instead of VMId+ASID, doesn't that unnecessarily limit the ASID space, with all downsides of that?

**Comment by lsf37** [comment]
> Code seems good to me. Just add the tqma IRQ fix and it's ready to go.

👍 now added.
 
> I don't understand why aarch64 is using VMID as ASID instead of VMId+ASID, doesn't that unnecessarily limit the ASID space, with all downsides of that?

I'm not sure, I was actually not aware that they could be combined. @kent-mcleod do you know more on that?

Non-hyp mode has a large enough hardware ASID space that we don't need any seL4 software ASID translation, which is also a bit easier on verification. But now that we've almost finished the proofs for all that, I'm not that keen to change it, at least not before this set of proofs is finished (which should be by end of March).

**Comment by kent-mcleod** [comment]
> I don't understand why aarch64 is using VMID as ASID instead of VMId+ASID, doesn't that unnecessarily limit the ASID space, with all downsides of that?

Can you be more specific? When seL4 is running in EL2, it only manages stage 2 mmu translation tables, the TLB entries for these mappings are tagged with the VMID.

Guest VCPUs are able to program stage 1 mmu and can then manage their own ASID allocations.

However native seL4 applications aren't able to program stage 1 mmu and so the logical seL4 VSpace is implemented only by stage 2 mmu translations. So only VMIDs are used and ASIDs are not used. Is this what you are referring to?

**Comment by Indanz** [comment]
> > I don't understand why aarch64 is using VMID as ASID instead of VMId+ASID, doesn't that unnecessarily limit the ASID space, with all downsides of that?
> 
> Can you be more specific? When seL4 is running in EL2, it only manages stage 2 mmu translation tables, the TLB entries for these mappings are tagged with the VMID.
> 
> Guest VCPUs are able to program stage 1 mmu and can then manage their own ASID allocations.
> 
> However native seL4 applications aren't able to program stage 1 mmu and so the logical seL4 VSpace is implemented only by stage 2 mmu translations. So only VMIDs are used and ASIDs are not used. Is this what you are referring to?

Yes, I assumed that ASIDs could be used for stage 2 translations too, and that the TLB would always check VMID+ASID. But it seems that only VMID is checked at stage 2 and that the ASID check is only done for stage 1 translations.

**Comment by lsf37** [comment]
Ok, so the VMID part is fine as is for now. We could maybe do more for v8.1, but that's a longer story.

I have added one more commit with more verification annotations (no code change). From my side, this is ready to merge once the seL4/l4v#703 is ready.

**Pull request merged**
