### PR TITLE
mcs: refactor cancelAllIPC and cancelBadgedSends

### PR DESCRIPTION
**Pull request by michaelmcinerney**
This factors out code from cancelAllIPC and cancelBadgedSends by introducing the inline function restart_thread_if_no_fault

### CODE REVIEW

**Review by lsf37 — APPROVED** [review]

**Review by Indanz — APPROVED** [review]

**Comment by Indanz** [comment]
Can this be merged or does it need to wait for verification?

**Comment by lsf37** [comment]
I think this still needs to wait for the corresponding l4v PR to be up. @michaelmcinerney is that correct?

**Comment by lsf37** [comment]
(Currently the tests on master are broken from the AArch64 debug API PR, so we should hold off on merging code PRs until that is fixed)

**Comment by michaelmcinerney** [comment]
> I think this still needs to wait for the corresponding l4v PR to be up. @michaelmcinerney is that correct?

I would be able to put together an l4v PR for this quite quickly, but I was waiting for the C to be merged first, maybe for no good reason. I'm quite sure that merging this wouldn't break tests for the `rt` branch on l4v, but I can put up the l4v PR over the next couple of days if we would like that first

**Comment by lsf37** [comment]
Better to do them simultaneously, but with the new `mcs` manifest handling we can actually check, I've started a proof test on the PR now.

**Pull request merged**
