### PR TITLE
output: use CR LF as line break and not LF CR

### PR DESCRIPTION
**Pull request by axel-h**

### CODE REVIEW

**Comment by axel-h** [comment]
I've been wondering about this for some time, is there a reason why LF CR is used and all kernel logs contain an empty line between each line (on many systems). Or is this just a mistake and it should always have been CR LF actually?

**Comment by kent-mcleod** [comment]
Nice find! I think it started out one way and then got copied across all the different serial drivers as they were added. I'm happy to get these merged. @ssrg-bamboo test

**Comment by axel-h** [comment]
rebased to latest master

**Comment by axel-h** [comment]
seems the bamboo bot does not act when you put the command into a comment

**Comment by kent-mcleod** [comment]
I think it does, but the first time I made the commend I didn't format it properly and then edited it later. But I guess the bot already processed the message as read, @ssrg-bamboo `test`.

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Pull request merged**
