### PR TITLE
risc-v: remove special handling for restoring tp

### PR DESCRIPTION
**Pull request by axel-h**
I can't find a reason why it is done in such a complicated way, when the RISC-V port was added in 83ba0847.

### CODE REVIEW

**Review by Indanz — APPROVED** [review]
No idea.

**Review by lsf37 — CHANGES_REQUESTED** [review]
Let's not merge this before we have found out. Not knowing is not a good enough reason to change something.

**Comment by Indanz** [comment]
> Let's not merge this before we have found out. Not knowing is not a good enough reason to change something.

Whatever it is, it warrants a comment. Only reason I can think of is that it's to work around a performance crippling quirk on a specific implementation. Another more far fetched reason is because Rust inline assembly didn't allow direct use of `tp` and that influenced @heshamelmatary (but the same is true for `gp` though).

FreeBSD](https://cgit.freebsd.org/src/tree/sys/riscv/riscv/exception.S#n143) and [OpenBSD](https://github.com/openbsd/src/blob/c7101648ccc694093c4a805ebde0f53056d1a24c/sys/arch/riscv64/riscv64/exception.S#L146) just load it too. Linux stores `tp` in `sscratch`.

**Comment by kent-mcleod** [comment]
It should be safe to make this change. 

It was most likely due to IPC buffer handling from before 11.0.0 (https://docs.sel4.systems/releases/sel4/11.0.0.html). 
Before this version, a thread-local register was reserved by the kernel for storing the pointer to the thread's IPC buffer which was the `tp` register on riscv. Architectures such as aarch64 would set the register inside `Arch_switchToThread()` and then not touch the register in `restore_user_context()`. 

When the RISC-V port was up-streamed, it didn't restore the register with the other registers, but also didn't restore it in `Arch_switchToThread()` and so ended up restoring it right at the end of the restore process.

**Comment by lsf37** [comment]
> It should be safe to make this change.
> [..]
> When the RISC-V port was up-streamed, it didn't restore the register with the other registers, but also didn't restore it in `Arch_switchToThread()` and so ended up restoring it right at the end of the restore process.

Thanks, that makes perfect sense. With that I'm happy with the change.

**Review by lsf37 — APPROVED** [review]

**Comment by lsf37** [comment]
It'd be good to record that reasoning in the commit message (i.e. that `tp` was used for thread-local storage before and since that is gone, the special handling is no longer necessary). Since it's uniform with the rest, we probably don't need a comment in the source for it, if the change reasoning is documented.

**Comment by axel-h** [comment]
> It'd be good to record that reasoning in the commit message (i.e. that `tp` was used for thread-local storage before and since that is gone, the special handling is no longer necessary). Since it's uniform with the rest, we probably don't need a comment in the source for it, if the change reasoning is documented.

done

**Comment by heshamelmatary** [comment]
I don't remember the reason, but @kent-mcleod remembers better than I do. It wasn't for Rust though as I haven't accounted for that. Should be fine to merge.

**Pull request merged**
