### PR TITLE
riscv: add wrapper read_sscratch()

### PR DESCRIPTION
**Pull request by axel-h**
hide assembly code behind a wrapper function

### CODE REVIEW

**Comment by axel-h** [comment]
Seems the proofs are fine with this.

**Review by lsf37 — APPROVED** [review]
No problem from the proof side, happy to remove a bit of duplication.

**Comment by lsf37** [comment]
This PR broke the sel4test hardware build -- see <https://github.com/seL4/seL4/actions/runs/8263995752/job/22606633755>.

Seems to be something trivial, can you please have a look?

**Comment by axel-h** [comment]
> I created #1221, hopefully that fixes it.

Thanks.

**Comment by Indanz** [comment]
Okay, that created a circular dependency, so it's not a fix. I propose to revert the smp.h change instead.

**Pull request merged**
