### PR TITLE
python: use '#paragma once' include guard

### PR DESCRIPTION
**Pull request by axel-h**
using the '#paragma once' include guard simplifies things a bit and it's the modern way to guard includes.

### CODE REVIEW

**Comment by pingerino** [comment]
IIRC I didn't do this as it didn't work for kernel headers (#pragma once does not work if we concatenate all of the c files together).

**Comment by axel-h** [comment]
> IIRC I didn't do this as it didn't work for kernel headers (#pragma once does not work if we concatenate all of the c files together).

This generates header files that are included. As far as I understand things,just the c-files are concatenated. The headers are still kept for the compiler to get pulled in, where it honors the `#pragma once` then. I can't see any traces from the header file contents in `kernel_all.c`. The compiler intermediate output `kernel_all.i` contains the header content eventually - but then exactly once, as expected.

**Comment by ratmice** [comment]
Not a officially recognized reviewer, but I believe that Axel is correct, and that perhaps the confusion is that while syscall_stub_gen.py generates functions, and function bodies.  It does so for inline functions which are then written to header files, so it should not impact the concatenation of source files.

**Comment by lsf37** [comment]
Axel is right, this one does work here and should be unified. We're already using `#pragma once` for the rest of the kernel headers and the preprocessed concatenated output is identical after this change.

**Review by lsf37 — APPROVED** [review]

**Review by kent-mcleod — APPROVED** [review]

**Pull request merged**
