### PR TITLE
Mask async aborts for idle thread in debug kernels

### PR DESCRIPTION
**Pull request by jdub**
Fixes seL4/seL4#33

### CODE REVIEW

**Comment by jdub** [comment]
I suppose it's a bit cheeky to say this fixes #33, as it was already partially fixed in b727ede2c5c054277bf386566d4d966254883620. But hey. 😳

**Comment by AdrianDanis** [comment]
Hi @jdub, thanks for the patch. As per the comments on #33 I think it would be much more preferable if this change was guarded by a config option, and not applied unilaterally to all debug builds.

**Comment by jdub** [comment]
As it doesn't actually resolve any of the problems I raised in #33, is it worth adding the option? Is there a legitimate reason someone might want it? Otherwise, I'm happy to let it go.

**Comment by AdrianDanis** [comment]
Certainly I'm happy to have the option added, but I cannot speak as to whether or not anyone else would actually want it.

**Comment by jdub** [comment]
Ha, okay. My philosophy is that options should clear a very high bar, so if you can't think of one, I'm done. :smile:

**Pull request closed without merging**
