### PR TITLE
risc-v: support rv32 targets for qemu-riscv-virt

### PR DESCRIPTION
**Pull request by axel-h**
Fix a build breaker.

Test with: seL4/ci-actions#234

### CODE REVIEW

**Comment by axel-h** [comment]
I wonder, is anybody using seL4 on RV32 at the moment? If so please let me know which platforms are out there that you work on. Thanks

**Review by kent-mcleod — APPROVED** [review]

**Review by lsf37 — APPROVED** [review]

**Comment by Ivan-Velickovic** [comment]
seL4test will build/pass with this patch: https://github.com/Ivan-Velickovic/seL4/commit/5bc7ad983bd1d04ccf3c41994a995af85109ca00 (in addition to this PR).

**Comment by lsf37** [comment]
Cool! @axel-h , could you add that commit to this PR? (assuming you're fine with that @Ivan-Velickovic)

**Review by lsf37 — APPROVED** [review]

**Comment by Ivan-Velickovic** [comment]
Giving QEMU 2GiB of RAM doesn't work, it needs to be less than 2GiB since `avail_p_regs` will refer to the end of memory, `0x10000000` in this case, which doesn't fit in a 32-bit word.

**Comment by axel-h** [comment]
Ture. Sorry, this slipped my tests. So currently we still get the error
```
kernel/gen_headers/plat/machine/devices_gen.h:49:18: error: unsigned conversion from 'long long int' to 'long unsigned int' changes value from '4294967296' to '0' [-Werror=overflow]
   49 |         .end   = 0x100000000
      |                  ^~~~~~~~~~~
```
instead of 
```
   49 |         .end   = 0x140000000
      |                  ^~~~~~~~~~~
```

Seems the most trivial fix really is just using '2047' in thge CMake scripts. But that does not solve the general problem that QEMU might be configures to have more memory, and seL4 should just ignore the space it can't handle. And even more general, any 32-bit platform should be allowd to have memory up to the end. Seems this would be addresses best in the Python scripts. For the RISC-V/ARM QEMU platforms, I'm looking into reserving all memory above '0xffffffff' in a dedicated 32-bit overlay DTS for the kernel. Then the scripts you adjust the usable regions to end a '0xffffffff'.

**Pull request merged**
