### PR TITLE
boot: use SEL4_PRIx_word instead of 'lx'

### PR DESCRIPTION
**Pull request by axel-h**

### CODE REVIEW

**Comment by mbrcknl** [comment]
Where is `SEL4_PRIx_word` defined?

**Comment by axel-h** [comment]
@mbrcknl: It's in `include/basic_types.h` and `libsel4/include/sel4/simple_types.h`. It's still an open point if using one common location would be possible.

**Comment by mbrcknl** [comment]
> @mbrcknl: It's in `include/basic_types.h` and `libsel4/include/sel4/simple_types.h`.

Oh, no wonder my recursive `grep` didn't find it... I was in the `l4v` directory! :-)

> It's still an open point if using one common location would be possible.

I guess we don't try to solve that here.

**Review by mbrcknl — APPROVED** [review]

**Comment by axel-h** [comment]
- rebased
- commit comment is even more verbose now.

**Review by lsf37 — APPROVED** [review]

**Pull request merged**
