### PR TITLE
x86: initialize variables

### PR DESCRIPTION
**Pull request by nspin**
Multiple versions of GCC were unable to determine that these variables in `decodeX86PortInvocation` are initialized in all cases.

Oddly, this compilation failure was only observed with `-O1`. Compilation with `-O2` was not failing.

### CODE REVIEW

**Comment by nspin** [comment]
I've opened https://github.com/seL4/l4v/pull/825 to update the `X64` C refinement proof.

**Comment by Indanz** [comment]
Is this needed for binary verification?

**Comment by nspin** [comment]
No, the `X64` configuration isn't in scope for binary verification.

**Comment by kent-mcleod** [comment]
> Oddly, this compilation failure was only observed with `-O1`. Compilation with `-O2` was not failing.

I think there are a few cases where the optimization level causes the statements to be cut due to not being used before whatever layer that generates the warning sees them.

**Review by kent-mcleod — APPROVED** [review]

**Review by lsf37 — APPROVED** [review]

**Pull request merged**
