### PR TITLE
Zcu102 7.0.0

### PR DESCRIPTION
**Pull request by Furao**
This pull request adds AARCH32 and AARCH64 support for the Xilinx Zynq UltraScale+ MPSoC. Tested on the ZCU102 development board.

### CODE REVIEW

**Comment by Furao** [comment]
Feel free to drop the "Added DARPA License" commit. We just need to retain it in our own repositories.

**Comment by AdrianDanis** [comment]
Hi @Furao 
Thanks for this and your other pull requests. At a quick glance they look really good and might have a couple of minor comments to make, but that would be all. Mostly I need to talk to people and work out what the best thing for us to do with the licenses is.

**Comment by AdrianDanis** [comment]
@Furao sorry for the delay. We have some tools we use to automate the querying and management of our license tags and been working out the best way to add in support for additional contributors/owners. Whilst this won't scale, until we can fix our tools our proposed solution is, where you currently have multiple `@TAG` lines to creating something like the following

```c
/*
 * Copyright 2017, DornerWorks
 * Copyright 2014, General Dynamics C4 Systems
 *
 * This software may be distributed and modified according to the terms of
 * the GNU General Public License version 2. Note that NO WARRANTY is provided.
 * See "LICENSE_GPLv2.txt" for details.
 *
 * @TAG(GD_DORNERWORKS_GPL)
 */
/*
 * This data was produced by DornerWorks, Ltd. of Grand Rapids, MI, USA under
 * a DARPA SBIR, Contract Number D16PC00107.
 *
 * Approved for Public Release, Distribution Unlimited.
 */
```

Having a single `@TAG` for multiple people will not scale, but will do fine for now until we can improve our tools. It would also be preferable if the SBIR attribution could be in a separate comment block. Is this acceptable?
This style would apply across all the PRs, not just this one.

**Comment by Furao** [comment]
Sorry for my delay as well on the rest of the comments. I thought there would just be some minor fixes, but ran into a couple of issues, so I am still working those out, but hope to have a rev2 up next week. Your proposed change to the licensing seems fine to me.

**Comment by Furao** [comment]
Updated based on comments.

**Comment by AdrianDanis** [comment]
@Furao thanks a lot for updating, especially the licenses. Have merged internally (this and all the other PRs), will come out once CI is done. Whilst certainly not required, if you feel like adding any information to the [list of supported hardware platforms](https://wiki.sel4.systems/Hardware), that would be great

**Comment by Furao** [comment]
@AdrianDanis I tried to modify that wiki page, but it said, "You are not allowed to edit this page!"

**Comment by AdrianDanis** [comment]
@Furao Sorry about that, there was a problem with your account creation. It should be fixed now if you would like to try again

**Pull request merged**
