### PR TITLE
remove redundant defines

### PR DESCRIPTION
**Pull request by axel-h**
These defines seem redundant, they exist the architecture specific `bootinho.h` already and this seems the better place due to the subtle differences

### CODE REVIEW

**Comment by axel-h** [comment]
Seems even github has hiccups `fatal: unable to access 'https://github.com/seL4/seL4.git/': Failed to connect to github.com port 443: Connection timed out`

**Comment by lsf37** [comment]
> Seems even github has hiccups `fatal: unable to access 'https://github.com/seL4/seL4.git/': Failed to connect to github.com port 443: Connection timed out`

Huh, I've seen a few of these recently locally, but I though that was my home network. Maybe it wasn't. I'll rerun the tests.

**Comment by kent-mcleod** [comment]
Context: https://sel4.discourse.group/t/why-is-max-num-freemem-reg-defined-in-two-different-places/330

**Review by kent-mcleod — APPROVED** [review]

**Comment by axel-h** [comment]
@kent-mcleod: in my local patch set I'm considering deleting the architecture's `bootinho.h` because
- the content could be put into the existings architecture's `arch/kernel/boot.h` also
- there is a architecture agnostic `bootinfo.h` and having the `arch/bootingo.h`files is confusing.

**Comment by axel-h** [comment]
Test SCHED0021 failed on PC99_debug_gcc_64, but I think this is related to my changes here.

**Comment by lsf37** [comment]
The simulation test worked after re-run which confirms that it's the known SCHED0021 issue.

**Pull request merged**
