### PR TITLE
avoid pointer arithmetic

### PR DESCRIPTION
**Pull request by axel-h**

### CODE REVIEW

**Comment by Indanz** [comment]
What is the motivation for this change, other than making the code slightly better at the cost of extra effort updating the verification?

**Comment by lsf37** [comment]
The `&intStateIRQNode[idx]` construction would make the term in the proof much more annoying. This should not be merged.

**Comment by axel-h** [comment]
Out of curiosity, why does this make the proof harder actually?

**Comment by lsf37** [comment]
The array index operator wants the object to be an array, and the address-of operator then has to back-simulate the original pointer arithmetic just to get to what the original source said. The original is just clear and direct in the proof.

I do actually also find it much clearer in C, but that's not that important.

**Pull request closed without merging**
