### PR TITLE
Refactor github workflows; add preprocess test

### PR DESCRIPTION
**Pull request by lsf37**
This commit refactors the github workflows into two file (push/pull request), makes use of the new central seL4 github actions, and adds the preprocess test for pull requests.

This PR itself is a test whether these all work also from forked repositories.

### CODE REVIEW

**Comment by lsf37** [comment]
Well, it looks like the gitlint check needs more work.

**Comment by lsf37** [comment]
Ok, ready for you to have a look at @kent-mcleod

**Comment by lsf37** [comment]
(The changes happened in the https://github.com/seL4/ci-actions repo)

**Comment by kent-mcleod** [comment]
How long does preprocess builds typically take?

**Comment by lsf37** [comment]
The 2min it has here should be typical. When it fails, it doesn't run the proofs, though -- I have a CI action for that, but it turns out the github VMs are too small (only 7GB RAM).

**Comment by lsf37** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by lsf37** [comment]
Merged in ab5b6bd6bf3e7029f9511734531b3372e0e884e8

**Pull request closed without merging**
