### PR TITLE
add CONFIG_PRINTING to DEBUG build

### PR DESCRIPTION
**Pull request by zhicheng**
fix typo: src/plat/pc99/machine/acpi.c, ACIP should be ACPI

### CODE REVIEW

**Comment by AdrianDanis** [comment]
I don't understand the line 'source and binary changed' in the commit message

**Comment by zhicheng** [comment]
this patch will generate different binary. notify current user.

**Comment by AdrianDanis** [comment]
Just about any of the commits in this repository would lead to a different binary. I think this line is confusing and unnecessary, could you please remove it?

**Comment by AdrianDanis** [comment]
@zhicheng sorry not responding to this, github helpfully didn't notify me that you had added a commit. This will get merged once it gets through continuous integration

**Pull request merged**
