### PR TITLE
trivial: fix typos in comment

### PR DESCRIPTION
**Pull request by axel-h**

### CODE REVIEW

**Review by lsf37 — APPROVED** [review]

**Comment by lsf37** [comment]
Thanks for the fix -- please don't add `hw-test` for comment PRs, there is only a limited number of boards and all hardware tests in the seL4 org compete for them.

**Comment by axel-h** [comment]
I've added the label to have a reference run for the other pending PRs.

**Comment by lsf37** [comment]
Fair enough, they have been failing a lot. All runs should succeed, apart from this one: https://github.com/seL4/sel4test/issues/64 (I *think* have seen it succeeding in the new build environment, but it fails a lot and really shouldn't)

**Comment by axel-h** [comment]
But using the label here was not necessary indeed, there seems to be the deps-update that acts as reference. The status of it is just hidden a bit. Maybe having a more prominent status page of it similar to the benchmark history idea https://github.com/seL4/website/issues/158 would be handy.

**Comment by lsf37** [comment]
Yes, although in theory these are the tests that should be always passing. In practice, theory and practice are not the same :-)

**Pull request merged**
