### PR TITLE
manual: fix VM attributes documentation

### PR DESCRIPTION
**Pull request by Ivan-Velickovic**
Closes https://github.com/seL4/seL4/issues/1039.

### CODE REVIEW

**Review by lsf37 — APPROVED** [review]
Awesome, that was quick, thank you!

If you're up for it, could you add that the ia32 attribtues also apply to ia64 and that `ARM_ParityEnabled` is ignored on AArch64? I can also do a separate PR for that if needed.

**Comment by Ivan-Velickovic** [comment]
> Awesome, that was quick, thank you!
> 
> If you're up for it, could you add that the ia32 attribtues also apply to ia64 and that `ARM_ParityEnabled` is ignored on AArch64? I can also do a separate PR for that if needed.

Done

**Comment by Ivan-Velickovic** [comment]
> Awesome, that was quick, thank you!
> 
> If you're up for it, could you add that the ia32 attribtues also apply to ia64 and that `ARM_ParityEnabled` is ignored on AArch64? I can also do a separate PR for that if needed.

Done

**Review by lsf37 — APPROVED** [review]
:+1:

**Pull request merged**
