### PR TITLE
mcs: use sc_active in commitTime

### PR DESCRIPTION
**Pull request by michaelmcinerney**

### CODE REVIEW

**Review by lsf37 — APPROVED** [review]
👍

**Review by Indanz — APPROVED** [review]
There's also src/api/syscall.c:485, src/fastpath/fastpath.c:666 and src/object/schedcontrol.c:39 and some asserts.

**Comment by Xaphiosis** [comment]
> There's also src/api/syscall.c:485, src/fastpath/fastpath.c:666 and src/object/schedcontrol.c:39 and some asserts.

Would be good to catch these as well. One day we might hit MCS fastpath.

**Comment by lsf37** [comment]
I'm going to merge this one as is, but I agree it'd be good to do the other instances as well, and more systematically. Will put that on the todo list.

**Pull request merged**
