### PR TITLE
Disable L2 cache during initialisation

### PR DESCRIPTION
**Pull request by jdub**
Fixes seL4/seL4#41.

### CODE REVIEW

**Comment by AdrianDanis** [comment]
Hey @jdub thanks so much for tracking this down. Unfortunately this is the part where I point out that our [contributions](http://sel4.systems/Community/Contributing/) require a CLA. I hope this is possible.

**Comment by jdub** [comment]
*insert grumbling about having to sign a CLA at all, worse yet with a military contractor* Fiiiiine.

Does that document need updating since the NICTA → Data61 change? (It still mentions NIPR.)

**Comment by AdrianDanis** [comment]
Yeah the CLA thing is a giant pain. I enjoy checking/asking for them about as much as you enjoy signing them.

I asked about this recently and was told we are still using that document with NICTA on it.

**Comment by jdub** [comment]
Signed and sent.

**Pull request merged**
