### PR TITLE
boot: don't enforcing defining MODE_RESERVED

### PR DESCRIPTION
**Pull request by axel-h**
On AARCH32 there is a special need for an ASID region. Since no other architecture needs this mechanism, handle this within the AARCH32 specific code and keep the generic code clean.

### CODE REVIEW

**Comment by lsf37** [comment]
From the verification side, I'm relatively neutral on this, although I'd prefer the fewer `#ifdef`s of the old version.

From the code side, I'm not entirely convinced that this is really cleaner than before. Isn't it nicer to have the concept of a potential extra region for arch specific code? Currently only Arm32 needs it, but that might not stay that way forever, the current set of architectures is not all that could be supported in the future. It doesn't look like the new code is much shorter either.

Happy to be convinced otherwise, but so far I don't see it meeting the benefit threshold yet.

**Comment by kent-mcleod** [comment]
> On AARCH32 there is a special need for an ASID region. Since no other architecture needs this mechanism, handle this within the AARCH32 specific code and keep the generic code clean.

AARCH32 isn't the only arch with this need.  Any platform that has less hardware ASIDs than seL4 ASIDs will require a way of linking the HW ASID with root pagetable object. Currently this can only be achieved by reserving a slot in the root page table and making it an invalid mapping that also holds the current hw_asid. aarch32 isn't the only architecture that has this constraint. RISC-V will need this once a CPU is added that has HWASIDs but less than 16bits of ASID space and greater than 1Bit of asid space.

**Comment by axel-h** [comment]
@kent-mcleod: Thanks for the explanation. I think we can still add for RISC-V after my changes easily.
@lsf37: The main motivation for this is removing defines that are just dummies in some architectures and make the generic code simpler by forcing platforms/architectures to set the defines right. I have more patches on top of this that would allow removing the `#ifdef` eventually and use helper functions the for the memory setup.

**Comment by yyshen** [comment]
> From the verification side, I'm relatively neutral on this, although I'd prefer the fewer `#ifdef`s of the old version.
> 
> From the code side, I'm not entirely convinced that this is really cleaner than before. Isn't it nicer to have the concept of a potential extra region for arch specific code? Currently only Arm32 needs it, but that might not stay that way forever, the current set of architectures is not all that could be supported in the future. It doesn't look like the new code is much shorter either.
> 
> Happy to be convinced otherwise, but so far I don't see it meeting the benefit threshold yet.

@lsf37 I think the changes also need reverification effort which seems not trivial?

**Comment by axel-h** [comment]
I've reworked this now. It's split it in a set of changes that add comments and some refactoring to reduce global dependencies. That will also be helpful for further changes. The ARM part is left as it is as much as possible and `MODE_RESERVED` is not removed there. The changes left out from this PR are parked in https://github.com/axel-h/seL4/commits/patch-axel-14a. Depending how the other merges go, these change can be dropped anyway, as I'm aiming for a generic function `reserve_region()` that can be called in various places in the boot code. It handles managing/merging the reserved regions internally then, so no care needs to be taken about the order when calling it. That make handling dynamically reserved areas on all architectures much easier.

**Comment by axel-h** [comment]
can we merge this?

**Comment by kent-mcleod** [comment]
> can we merge this?

Just checking the proofs are happy with the extra +0 and if blocks

**Review by kent-mcleod — APPROVED** [review]

**Pull request merged**
