### PR TITLE
tools: fix brackets in format parameters

### PR DESCRIPTION
**Pull request by axel-h**
Signed-off-by: Axel Heider <axelheider@gmx.de>

### CODE REVIEW

**Comment by axel-h** [comment]
This fixes a bug in the script, is there anything that blocks merging this?

**Comment by axel-h** [comment]
seem I'm not the only one running into this issue, see https://github.com/seL4/seL4/pull/191

**Comment by lsf37** [comment]
@ssrg-bamboo test

**Comment by lsf37** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
