### PR TITLE
arm: flush cache to RAM on retype reset

### PR DESCRIPTION
**Pull request by lsf37**
This fixes a correctness and security issue where uncached user mappings might see old data from before the clearMemory operation.

See also the discussion on GitHub issue #481 and corresponding seL4/sel4test#45

### CODE REVIEW

**Review by kent-mcleod — APPROVED** [review]

**Comment by lsf37** [comment]
I'll rebase to remove the merge commit and get the new cache test included in the hw test.

**Comment by lsf37** [comment]
This is ready to merge once the proofs are updated.

**Comment by lsf37** [comment]
Verification reminded us that `clearMemory` is not only called in retype. So there are two `clearMemory` versions now for Arm: the default flushes to RAM, and basically the old version that flushes to PoU, which is used for page table operations.

**Comment by lsf37** [comment]
Free proof update in seL4/l4v#326, courtesy of [Proocraft](https://proofcraft.systems).

When that is approved, we can merge.

**Pull request merged**
