### PR TITLE
mcs: correct MinSchedContextBits and add compile assert

### PR DESCRIPTION
**Pull request by michaelmcinerney**
Signed-off-by: Michael McInerney <michael.mcinerney@proofcraft.systems>

### CODE REVIEW

**Comment by michaelmcinerney** [comment]
Updated and force pushed to hopefully solve the failure of the compile assert that was occurring. I think it was just that `seL4_CoreSchedContextBytes` had not been declared yet.

**Review by lsf37 — APPROVED** [review]
Have changed the `compile_assert` to `SEL4_COMPILE_ASSERT` since this under libsel4. Otherwise happy with the change, this should allow us to see immediately when the size diverges in the future.

**Comment by lsf37** [comment]
(rebased)

**Comment by lsf37** [comment]
@kent-mcleod happy for us to merge this one?

**Review by kent-mcleod — APPROVED** [review]

**Pull request merged**
