### PR TITLE
small python config handling improvements

### PR DESCRIPTION
**Pull request by axel-h**
- reduce redundancy in config selection
- reverse config class names. The naming is more intuitive this way and the classes show up together in the IDE outline.

### CODE REVIEW

**Comment by lsf37** [comment]
Can't really say I'm in favour of this one.

> * reduce redundancy in config selection

I don't see any reduction in redundancy. The name `sel4arch` is mentioned one times less, but I find the previous structure clearer. The new one is not wrong or anything, but it's not better.

> * reverse config class names. The naming is more intuitive this way and the classes show up together in the IDE outline.

My IDE already shows them next to each other. In fact, there are only three classes, so I don't think this is a good argument for code churn.

**Comment by axel-h** [comment]
> I don't see any reduction in redundancy. The name sel4arch is mentioned one times less, but I find the previous structure clearer. The new one is not wrong or anything, but it's not bette

Basically, this change come from some experimenting with adding more architectures. It scales a bit better, because new classes can be added as a line to the array then.

**Comment by lsf37** [comment]
> Basically, this change come from some experimenting with adding more architectures. It scales a bit better, because new classes can be added as a line to the array then.

I don't really see that, to me it scales exactly the same: you either add an additional `ifelse` branch or you add a line.

**Comment by axel-h** [comment]
It's more "pythonic" ;)

**Comment by kent-mcleod** [comment]
> * reduce redundancy in config selection
> 
> * reverse config class names. The naming is more intuitive this way and the classes show up together in the IDE outline.

A PR wouldn't be blocked from being merged based on these requirements. As these changes aren't fixing an existing problem or adding new functionality I don't think they should be merged. We aren't about to add any new architectures so trying to make the code ready for something we aren't actively planning for isn't a good use of limited attention spans.

**Comment by axel-h** [comment]
Closing this based on the feedback

**Pull request closed without merging**
