### PR TITLE
aarch64: Use isb after changing FPU control registers

### PR DESCRIPTION
**Pull request by yyshen**
Signed-off-by: Yanyan Shen <yshen@hybridkernel.com>

### CODE REVIEW

**Comment by yyshen** [comment]
@lsf37 The preprocess step needs some changes.

**Comment by kent-mcleod** [comment]
I thought that these register system control register updates only affected execution at lower execution levels and so a return-from-exception would already be sufficient to synchronize the updates to these registers?

**Comment by kent-mcleod** [comment]
To elaborate, looking in the ARM Cortex-A programmers guide for ARMv8, there's a section on `isb`s: [13.2.2 ISB in more detail](https://developer.arm.com/documentation/den0024/a/Memory-Ordering/Barriers/ISB-in-more-detail)

It actually uses updating `CPACR_EL1` as an example where an isb is required after, but I assume that this is when EL1 is the current EL.

**Comment by yyshen** [comment]
> I thought that these register system control register updates only affected execution at lower execution levels and so a return-from-exception would already be sufficient to synchronize the updates to these registers?

The EL2 code enables/disables access to FPU before/after it calls saveFpuState/loadFpuState. On some processors, without the ISB, accessing the FPU triggers an kernel exception.

**Review by mbrcknl — COMMENTED** [review]
The proposed changes should not affect any proofs, since these functions would be below the level of our machine model. In any case, I suspect aarch64 verification has not yet reached C refinement. @lsf37 should be able to confirm.

If you and @kent-mcleod decide that this should be merged, you would need to ignore the preprocess failure. Once this is merged, I can bump the verification manifest.

**Comment by yyshen** [comment]
> The proposed changes should not affect any proofs, since these functions would be below the level of our machine model. In any case, I suspect aarch64 verification has not yet reached C refinement. @lsf37 should be able to confirm.
> 
> If you and @kent-mcleod decide that this should be merged, you would need to ignore the preprocess failure. Once this is merged, I can bump the verification manifest.

Thank you for checking.

**Comment by lsf37** [comment]
Yes, can confirm that this is fine for verification (and will need a preprocess bump)

**Comment by yyshen** [comment]
@kent-mcleod I would like to merge it if you have no objections.

**Comment by kent-mcleod** [comment]
> The EL2 code enables/disables access to FPU before/after it calls saveFpuState/loadFpuState. On some processors, without the ISB, accessing the FPU triggers a kernel exception.

Ok, I can see that it's needed on updates to cptr_el2 that change access from EL2. Why is the ISB needed for the updates to cpacr_el1 also?

**Comment by yyshen** [comment]
> > The EL2 code enables/disables access to FPU before/after it calls saveFpuState/loadFpuState. On some processors, without the ISB, accessing the FPU triggers a kernel exception.
> 
> Ok, I can see that it's needed on updates to cptr_el2 that change access from EL2. Why is the ISB needed for the updates to cpacr_el1 also?

https://github.com/seL4/seL4/blob/d57b2cd0f8a09bf6168f2db39b261651559422a9/include/arch/arm/arch/64/mode/machine/fpu.h#L123

enableFpuEL01 is also called before saving/restoring FPU state without an exception level change.

**Comment by kent-mcleod** [comment]
> enableFpuEL01 is also called before saving/restoring FPU state without an exception level change.

Ok.  disableFpu() doesn't disable the FPU for EL1 when the kernel is operating at EL1.  But there's no explicit function that enables the FPU during kernel boot, so the first time that enableFPU is called could be enabling the FPU state at the same exception level?

**Review by kent-mcleod — APPROVED** [review]

**Comment by yyshen** [comment]
> > enableFpuEL01 is also called before saving/restoring FPU state without an exception level change.
> 
> Ok. disableFpu() doesn't disable the FPU for EL1 when the kernel is operating at EL1. But there's no explicit function that enables the FPU during kernel boot, so the first time that enableFPU is called could be enabling the FPU state at the same exception level?

Good point, the I was not inspecting the EL0/1 case carefully enough. It looks like we could have the EL1 access enabled all the time and only disable/enable EL0 access for lazy fpu switch, since we know the kernel itself does not use the FPU.

**Comment by yyshen** [comment]
@kent-mcleod I will merge the current one as it is, and see if I can come up a tuned version for EL1. Thanks

**Pull request merged**
