### PR TITLE
Streamline libsel4 and remove its libc dependencies.

### PR DESCRIPTION
**Pull request by winksaville**
There are now separate libs for benchmark, assert, printf, putchar
start/stop:

      libs/libsel4benchmark
      libs/libsel4assert
      libs/libsel4printf
      libs/libsel4putchar
      libs/libsel4startstop

The primary changes are introducing sel4/sel4.h and removing std* types
plus porting assert and IO code from the kernel to libsel4assert,
libsel4printf, libsel4putchar.

This means the code within libsel4 and the newlibs do not overload any
typical libc entities. Instead the libraries use types like
seL4_Uint32 ... instead of uint32_t. And printf is now seL4_Printf and
assert is seL4_Assert ....

Finally, the only file modified that effects kernel code is
kernel/tools/bitfield_gen.py. It needed to be modified as it generates
files for both kernel and user space. And for user space the generated code
(types_gen.h) needed to use the new types and asserts. The changes should
not change what is generated for the kernel and I did a comparison of
kernel_final.{c|s} before and after my change and the only differences
were time stamps.

Bug: #15 Streamline kernel/libsel4 and remove its libc dependencies

### CODE REVIEW

**Comment by heb1001** [comment]
The comments are incorrect in assert.h.

There are now separate libs for benchmark, assert, printf, putchar
start/stop:

  libs/libsel4benchmark
  libs/libsel4assert
  libs/libsel4printf
  libs/libsel4putchar
  libs/libsel4startstop

The primary changes are introducing sel4/sel4.h and removing std* types
plus porting assert and IO code from the kernel to libsel4assert,
libsel4printf, libsel4putchar.

This means the code within libsel4 and the newlibs do not overload any
typical libc entities. Instead the libraries use types like
seL4_Uint32 ... instead of uint32_t. And printf is now seL4_Printf and
assert is seL4_Assert ....

Finally, the only file modified that effects kernel code is
kernel/tools/bitfield_gen.py. It needed to be modified as it generates
files for both kernel and user space. And for user space the generated code
(types_gen.h) needed to use the new types and asserts. The changes should
not change what is generated for the kernel and I did a comparison of
kernel_final.{c|s} before and after my change and the only differences
were time stamps.

Bug: #15 <https://github.com/seL4/seL4/issues/15> Streamline kernel/libsel4
and remove its libc dependencies
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/seL4/seL4/pull/16
Commit Summary

   - Streamline libsel4 and remove its libc dependencies.

File Changes

   - *M* libsel4/Kbuild <https://github.com/seL4/seL4/pull/16/files#diff-0>
   (2)
   - *M* libsel4/Kconfig <https://github.com/seL4/seL4/pull/16/files#diff-1>
   (1)
   - *M* libsel4/arch_include/arm/interfaces/sel4arch.xml
   <https://github.com/seL4/seL4/pull/16/files#diff-2> (2)
   - *M* libsel4/arch_include/arm/sel4/arch/objecttype.h
   <https://github.com/seL4/seL4/pull/16/files#diff-3> (2)
   - *A* libsel4/arch_include/arm/sel4/arch/simple_types.h
   <https://github.com/seL4/seL4/pull/16/files#diff-4> (25)
   - *M* libsel4/arch_include/arm/sel4/arch/syscalls.h
   <https://github.com/seL4/seL4/pull/16/files#diff-5> (77)
   - *M* libsel4/arch_include/arm/sel4/arch/types.h
   <https://github.com/seL4/seL4/pull/16/files#diff-6> (5)
   - *M* libsel4/arch_include/x86/interfaces/sel4arch.xml
   <https://github.com/seL4/seL4/pull/16/files#diff-7> (26)
   - *M* libsel4/arch_include/x86/sel4/arch/functions.h
   <https://github.com/seL4/seL4/pull/16/files#diff-8> (7)
   - *M* libsel4/arch_include/x86/sel4/arch/objecttype.h
   <https://github.com/seL4/seL4/pull/16/files#diff-9> (3)
   - *M* libsel4/arch_include/x86/sel4/arch/pfIPC.h
   <https://github.com/seL4/seL4/pull/16/files#diff-10> (8)
   - *A* libsel4/arch_include/x86/sel4/arch/simple_types.h
   <https://github.com/seL4/seL4/pull/16/files#diff-11> (26)
   - *M* libsel4/arch_include/x86/sel4/arch/syscalls.h
   <https://github.com/seL4/seL4/pull/16/files#diff-12> (45)
   - *M* libsel4/arch_include/x86/sel4/arch/types.h
   <https://github.com/seL4/seL4/pull/16/files#diff-13> (4)
   - *M* libsel4/include/interfaces/sel4.xml
   <https://github.com/seL4/seL4/pull/16/files#diff-14> (60)
   - *A* libsel4/include/sel4/assert.h
   <https://github.com/seL4/seL4/pull/16/files#diff-15> (52)
   - *D* libsel4/include/sel4/benchmark.h
   <https://github.com/seL4/seL4/pull/16/files#diff-16> (48)
   - *M* libsel4/include/sel4/bootinfo.h
   <https://github.com/seL4/seL4/pull/16/files#diff-17> (10)
   - *A* libsel4/include/sel4/debug_assert.h
   <https://github.com/seL4/seL4/pull/16/files#diff-18> (36)
   - *M* libsel4/include/sel4/objecttype.h
   <https://github.com/seL4/seL4/pull/16/files#diff-19> (2)
   - *M* libsel4/include/sel4/sel4.h
   <https://github.com/seL4/seL4/pull/16/files#diff-20> (11)
   - *A* libsel4/include/sel4/simple_types.h
   <https://github.com/seL4/seL4/pull/16/files#diff-21> (29)
   - *M* libsel4/include/sel4/types.h
   <https://github.com/seL4/seL4/pull/16/files#diff-22> (1)
   - *R* libsel4/src/sel4_bootinfo.c
   <https://github.com/seL4/seL4/pull/16/files#diff-23> (5)
   - *M* libsel4/tools/syscall_stub_gen.py
   <https://github.com/seL4/seL4/pull/16/files#diff-24> (45)
   - *M* tools/bitfield_gen.py
   <https://github.com/seL4/seL4/pull/16/files#diff-25> (105)

Patch Links:

   - https://github.com/seL4/seL4/pull/16.patch
   - https://github.com/seL4/seL4/pull/16.diff

—
Reply to this email directly or view it on GitHub
<https://github.com/seL4/seL4/pull/16>.

**Comment by winksaville** [comment]
I've created a new libsel4printf with a BSD license and added libsel4string. Below are links to all of the new libraries:

  - https://github.com/winksaville/libsel4assert
  - https://github.com/winksaville/libsel4benchmark
  - https://github.com/winksaville/libsel4printf
  - https://github.com/winksaville/libsel4putchar
  - https://github.com/winksaville/libsel4startstop
  - https://github.com/winksaville/libsel4string

Below is test-nolibc which has some tests for all of the libraries we may want to incorporate
this as a series of tests in seL4test, if thats the direction you'd like to go I can prepare those tests:

  - https://github.com/winksaville/sel4-app-test-nolibc

Finally, below are links to 3 other lib's with one line modifications to include missing headers that are no longer in libsel4:

  - https://github.com/seL4/libsel4utils/pulls
  - https://github.com/seL4/libsel4test/pulls
  - https://github.com/seL4/libsel4allocman/pulls

**Comment by Smattr** [comment]
There are a couple of issues I raised previously that are still unresolved from my perspective. Namely:

* Why do we need a separate library for the benchmarking syscalls? Can this code not be merged into [libsel4bench](https://github.com/seL4/libsel4bench)?
* The halt implementation is unsuitable for any multiprocess environment. Do we even need this wrapper?

Some further things:

* The printf implementation looks unnecessarily obtuse to me. E.g. why does it throw a runtime error in the form of printed text when your pointers are an unexpected size? More to the point though, I still maintain it is not productive to re-implement printf purely for debugging. Just make users link against libc if they want printf. @AdrianDanis, please contradict me if desired.
* These changes add yet another level of indirection to putchar. I'm not saying this is unambiguously negative, but newcomers already find the printf call chain confusing and this will do nothing to improve that situation.

The three pull requests you reference for other libraries are orthogonal to this change and IMHO can be merged now.

----

Stepping back a little, what is your underlying use case for these changes? I ask because I'm wondering if you even want the helper functions (`seL4_GetCapReceivePath` and friends) or if you really just want just the syscall stubs. If your use case is running non-C languages on seL4, maybe you even want a native-ish implementation of the syscall stubs in your source language (e.g. inline assembly in Rust).

**Comment by AdrianDanis** [comment]
I agree with the benchmark log code being removed from `libsel4`, but I think I agree with @Smattr in that an entirely new library for it is a bit of overkill. What about shoving it in [`libsel4utils`](https://github.com/seL4/libsel4utils)? It's a dumping ground for general routines on seL4

Otherwise, as I said on the mailing list previously, the rest of the changes look good. Although I would like a chance to play with them a bit locally, which might take me a bit of time as I'm rather busy at the moment. I also want to leave this open a bit for others to comment.

Regarding the additional libraries. We currently have no desire to be the hosts/owners/maintainers of any additional libc implementations at the moment. While we are happy to make any changes to our libraries to make it possible for you to do this (such as this `libsel4` change), for now the rest remains your project.

**Comment by winksaville** [comment]
Tomorrow I'll move the benchmark header to libsel4utils and you play with
the code as long as you need, just let me know what else you'd like me to
do. And I understand the reluctance in taking the other code since it
probably doesn't offer any value over what's there from your perspective.

From my perspective I see the value in that the "new libraries" are
smaller. Anyway, I really appreciate you contemplating taking the changes,
I think it will allow others to more easily build on top of libsel4.

**Comment by winksaville** [comment]
I've created a pull request for benchmark.ha;

https://github.com/seL4/libsel4utils/pull/3

**Pull request merged**
