### PR TITLE
allow specific printf() formatting for seL4_Word

### PR DESCRIPTION
**Pull request by axel-h**
Turns out we need a  `SEL4_PRIx_word` also to print values in hex. So this adds it and makes `SEL4_PRI_word` use "SEL4_PRIu_word" then. Furthermore there is `_seL4_word_fmt`, which can be used to define further custom types.

### CODE REVIEW

**Review by kent-mcleod — APPROVED** [review]

**Comment by axel-h** [comment]
Any chance to get this merged?

**Comment by lsf37** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 9dc191ad4db6011d12d7292ca63e8431bcc5ae1b

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - C Parser - EXT-axel-h-patch-axel-5-330 | FAILED |
| Code Quality - Check licenses - seL4 - EXT-axel-h-patch-axel-5-330 | SUCCESSFUL |
| Code Quality - Reuse License Check - seL4 - EXT-axel-h-patch-axel-5-330 | SUCCESSFUL |
| Code Quality - Signed-off-by - seL4 - EXT-axel-h-patch-axel-5-330 | FAILED |
| Code Quality - Style - seL4 - EXT-axel-h-patch-axel-5-330 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Kernel Compile - EXT-axel-h-patch-axel-5-330 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: Preprocess - EXT-axel-h-patch-axel-5-330 | SUCCESSFUL |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-axel-h-patch-axel-5-330 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - C Parser - EXT-axel-h-patch-axel-5-330 | Set GitHub Success/Fail [Run C-Parser] | 1 of 1 job failed |

**Job: Set notifications [Run C-Parser]**
Build logs

    21-Apr-2021 14:27:19	Build Code Quality - C Parser - EXT-axel-h-patch-axel-5-330 - Set notifications [Run C-Parser] #1 (CQ-CPARSE454-RUNCPARSERGHSTATUS-1) started building on agent odroid-xu4-1, bamboo version: 7.1.4
    21-Apr-2021 14:27:19	
    21-Apr-2021 14:27:19	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS
    21-Apr-2021 14:27:19	Executing build Code Quality - C Parser - EXT-axel-h-patch-axel-5-330 - Set notifications [Run C-Parser] #1 (CQ-CPARSE454-RUNCPARSERGHSTATUS-1)
    21-Apr-2021 14:27:19	Preparing artifact 'name.properties' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/. (location: .)
    21-Apr-2021 14:27:19	Artifact 'name.properties' prepared in 31.54 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/./name.properties
    21-Apr-2021 14:27:19	Preparing artifact 'sha.properties' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/. (location: .)
    21-Apr-2021 14:27:19	Artifact 'sha.properties' prepared in 16.91 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/./sha.properties
    21-Apr-2021 14:27:19	Preparing artifact 'success_Run_C-Parser_AARCH32CPARSE' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/. (location: .)
    21-Apr-2021 14:27:19	Artifact 'success_Run_C-Parser_AARCH32CPARSE' prepared in 7.999 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/./AARCH32CPARSE.Run_C-Parser.success
    21-Apr-2021 14:27:19	Preparing artifact 'success_Run_C-Parser_AARCH32HYPCPARSE' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/. (location: .)
    21-Apr-2021 14:27:19	Artifact 'success_Run_C-Parser_AARCH32HYPCPARSE' prepared in 7.804 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/./AARCH32HYPCPARSE.Run_C-Parser.success
    21-Apr-2021 14:27:19	Preparing artifact 'success_Run_C-Parser_AARCH64CPARSE' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/. (location: .)
    21-Apr-2021 14:27:19	Artifact 'success_Run_C-Parser_AARCH64CPARSE' prepared in 12.89 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/./AARCH64CPARSE.Run_C-Parser.success
    21-Apr-2021 14:27:19	Preparing artifact 'success_Run_C-Parser_AARCH64HYPCPARSE' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/. (location: .)
    21-Apr-2021 14:27:19	Artifact 'success_Run_C-Parser_AARCH64HYPCPARSE' prepared in 8.341 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/./AARCH64HYPCPARSE.Run_C-Parser.success
    21-Apr-2021 14:27:19	Preparing artifact 'success_Run_C-Parser_IA32CPARSE' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/. (location: .)
    21-Apr-2021 14:27:19	Artifact 'success_Run_C-Parser_IA32CPARSE' prepared in 7.110 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/./IA32CPARSE.Run_C-Parser.success
    21-Apr-2021 14:27:19	Preparing artifact 'success_Run_C-Parser_IA32VTXCPARSE' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/CQ-CPARSE454-RUNCPARSERGHSTATUS/. (location: .)
    21-Apr-2021 14:27:19	Failure in artifact preparation phase during processing of: Subscription for Non required shared artifact: [success_Run_C-Parser_IA32VTXCPARSE], pattern: [*.Run_C-Parser.success] anchored at: [.], destination: [.]
    21-Apr-2021 14:27:19	1 error(s) found when performing pre-build actions. 
    21-Apr-2021 14:27:19	Running on server: post build plugin 'NCover Results Collector'
    21-Apr-2021 14:27:19	Running on server: post build plugin 'Build Hanging Detection Configuration'
    21-Apr-2021 14:27:19	Running on server: post build plugin 'Clover Delta Calculator'
    21-Apr-2021 14:27:19	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    21-Apr-2021 14:27:19	All post build plugins have finished
    21-Apr-2021 14:27:19	Generating build results summary...
    21-Apr-2021 14:27:19	Saving build results to disk...
    21-Apr-2021 14:27:19	Store variable context...
    21-Apr-2021 14:27:19	Indexing build results...
    21-Apr-2021 14:27:19	Finished building CQ-CPARSE454-RUNCPARSERGHSTATUS-1.


| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Signed-off-by - seL4 - EXT-axel-h-patch-axel-5-330 | Check all commits have been Signed-Off-by | 1 of 1 job failed |

**Job: signedoff**
Build logs

    21-Apr-2021 13:57:23	Build Code Quality - Signed-off-by - seL4 - EXT-axel-h-patch-axel-5-330 - signedoff #1 (CQ-SEL4SIGNEDOFF208-SEL4SIGNEDOFFSIGNEDOFF-1) started building on agent A local agent 1, bamboo version: 7.1.4
    21-Apr-2021 13:57:23	I run on the Bamboo server!
    21-Apr-2021 13:57:23	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4SIGNEDOFF208-SEL4SIGNEDOFFSIGNEDOFF
    21-Apr-2021 13:57:23	Executing build Code Quality - Signed-off-by - seL4 - EXT-axel-h-patch-axel-5-330 - signedoff #1 (CQ-SEL4SIGNEDOFF208-SEL4SIGNEDOFFSIGNEDOFF-1)
    21-Apr-2021 13:57:23	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4SIGNEDOFF208-SEL4SIGNEDOFFSIGNEDOFF/. (location: .)
    21-Apr-2021 13:57:23	Artifact 'code' prepared in 12.66 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4SIGNEDOFF208-SEL4SIGNEDOFFSIGNEDOFF/./code.tar.gz
    21-Apr-2021 13:57:23	Running pre-build action: VCS Version Collector
    21-Apr-2021 13:57:23	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    21-Apr-2021 13:57:23	+ tar xf code.tar.gz --recursive-unlink
    21-Apr-2021 13:57:23	Finished task 'Untar code' with result: Success
    21-Apr-2021 13:57:23	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    21-Apr-2021 13:57:23	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4SIGNEDOFF208-SEL4SIGNEDOFFSIGNEDOFF
    21-Apr-2021 13:57:23	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    21-Apr-2021 13:57:23	Starting task 'Check commits have been signed-off' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    21-Apr-2021 13:57:23	+ cd seL4
    21-Apr-2021 13:57:23	+++ git merge-base 9dc191ad4db6011d12d7292ca63e8431bcc5ae1b c64867ebdff00c4c2fd3145560457269483a5cd4
    21-Apr-2021 13:57:23	++ git rev-list --invert-grep --grep=Signed-off-by: c64867ebdff00c4c2fd3145560457269483a5cd4..9dc191ad4db6011d12d7292ca63e8431bcc5ae1b
    21-Apr-2021 13:57:23	+ commits_not_signed_off=9dc191ad4db6011d12d7292ca63e8431bcc5ae1b
    21-Apr-2021 13:57:23	+ '[' '!' -z 9dc191ad4db6011d12d7292ca63e8431bcc5ae1b ']'
    21-Apr-2021 13:57:23	+ echo 'The follow commits need to be signed off:'
    21-Apr-2021 13:57:23	+ echo 9dc191ad4db6011d12d7292ca63e8431bcc5ae1b
    21-Apr-2021 13:57:23	+ exit 1
    21-Apr-2021 13:57:23	The follow commits need to be signed off:
    21-Apr-2021 13:57:23	9dc191ad4db6011d12d7292ca63e8431bcc5ae1b
    21-Apr-2021 13:57:23	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-SEL4SIGNEDOFF208-SEL4SIGNEDOFFSIGNEDOFF-1-ScriptBuildTask-6417245506394621297.sh] was 1 while expected 0
    21-Apr-2021 13:57:23	Finished task 'Check commits have been signed-off' with result: Failed
    21-Apr-2021 13:57:23	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    21-Apr-2021 13:57:23	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4SIGNEDOFF208-SEL4SIGNEDOFFSIGNEDOFF
    21-Apr-2021 13:57:23	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    21-Apr-2021 13:57:23	Starting task 'Run dco code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    21-Apr-2021 13:57:23	+ cd seL4
    21-Apr-2021 13:57:23	++ echo ssh://git@bitbucket.ts.data61.csiro.au:7999/sel4/sel4.git
    21-Apr-2021 13:57:23	++ cut -d/ -f4
    21-Apr-2021 13:57:23	+ bb_proj=sel4
    21-Apr-2021 13:57:23	+ /scripts/bb_code_insights/create_code_insights.sh git-commits-signed-off sel4 seL4
    21-Apr-2021 13:57:23	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    21-Apr-2021 13:57:23	+ SCRIPT_DIR=/scripts/bb_code_insights
    21-Apr-2021 13:57:23	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    21-Apr-2021 13:57:23	+ BBS_PROJECT=sel4
    21-Apr-2021 13:57:23	+ BBS_REPO=seL4
    21-Apr-2021 13:57:23	+ REPORT_TO_RUN=git-commits-signed-off
    21-Apr-2021 13:57:23	++ git rev-parse HEAD
    21-Apr-2021 13:57:23	+ COMMIT_ID=9dc191ad4db6011d12d7292ca63e8431bcc5ae1b
    21-Apr-2021 13:57:23	+ REPORT_KEY=git-commits-signed-off.report
    21-Apr-2021 13:57:23	+ set +x
    21-Apr-2021 13:57:23	+ report_file=git-commits-signed-off_report.json
    21-Apr-2021 13:57:23	+ annotations_file=git-commits-signed-off_annotations.json
    21-Apr-2021 13:57:23	+ rm -f git-commits-signed-off_report.json git-commits-signed-off_annotations.json
    21-Apr-2021 13:57:23	+ /scripts/bb_code_insights/git-commits-signed-off
    21-Apr-2021 13:57:23	Running: git merge-base 9dc191ad4db6011d12d7292ca63e8431bcc5ae1b c64867ebdff00c4c2fd3145560457269483a5cd4
    21-Apr-2021 13:57:23	c64867ebdff00c4c2fd3145560457269483a5cd4
    21-Apr-2021 13:57:23	Running: git rev-list --invert-grep --grep=Signed-off-by: c64867ebdff00c4c2fd3145560457269483a5cd4..9dc191ad4db6011d12d7292ca63e8431bcc5ae1b
    21-Apr-2021 13:57:23	9dc191ad4db6011d12d7292ca63e8431bcc5ae1b
    21-Apr-2021 13:57:23	Identified bad commits:
    21-Apr-2021 13:57:23	[]
    21-Apr-2021 13:57:23	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    21-Apr-2021 13:57:23	+ set +x
    21-Apr-2021 13:57:23	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    21-Apr-2021 13:57:23	+ '[' -f git-commits-signed-off_report.json ']'
    21-Apr-2021 13:57:23	+ cat git-commits-signed-off_report.json
    21-Apr-2021 13:57:23	+ '[' -f git-commits-signed-off_annotations.json ']'
    21-Apr-2021 13:57:23	{"data":[{"title":"Total number of commits not signed-off","value":0,"type":"NUMBER"}],"createdDate":1618977443605,"details":"All good B-)","key":"git-commits-signed-off.report","result":"PASS","title":"Signed-off commits"}{"title": "Signed-off commits", "data": [{"title": "Total number of commits not signed-off", "value": 0, "type": "NUMBER"}], "details": "All good B-)", "result": "PASS"}
    21-Apr-2021 13:57:23	Finished task 'Run dco code insights' with result: Success
    21-Apr-2021 13:57:23	Running post build plugin 'NCover Results Collector'
    21-Apr-2021 13:57:23	Running post build plugin 'Artifact Copier'
    21-Apr-2021 13:57:23	Running post build plugin 'npm Cache Cleanup'
    21-Apr-2021 13:57:23	Running post build plugin 'Clover Results Collector'
    21-Apr-2021 13:57:23	Running post build plugin 'Docker Container Cleanup'
    21-Apr-2021 13:57:23	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-SEL4SIGNEDOFF208-SEL4SIGNEDOFFSIGNEDOFF'
    21-Apr-2021 13:57:23	Finalising the build...
    21-Apr-2021 13:57:23	Stopping timer.
    21-Apr-2021 13:57:23	Build CQ-SEL4SIGNEDOFF208-SEL4SIGNEDOFFSIGNEDOFF-1 completed.
    21-Apr-2021 13:57:23	Running on server: post build plugin 'NCover Results Collector'
    21-Apr-2021 13:57:23	Running on server: post build plugin 'Build Hanging Detection Configuration'
    21-Apr-2021 13:57:23	Running on server: post build plugin 'Clover Delta Calculator'
    21-Apr-2021 13:57:23	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    21-Apr-2021 13:57:23	All post build plugins have finished
    21-Apr-2021 13:57:23	Generating build results summary...
    21-Apr-2021 13:57:23	Saving build results to disk...
    21-Apr-2021 13:57:23	Store variable context...
    21-Apr-2021 13:57:23	Indexing build results...
    21-Apr-2021 13:57:23	Finished building CQ-SEL4SIGNEDOFF208-SEL4SIGNEDOFFSIGNEDOFF-1.


| Project | Stage | Result summary |
| --- | --- | --- |
| Dev seL4 tests - seL4 PRs: compile seL4test - EXT-axel-h-patch-axel-5-330 | Set GitHub Success/Fail [Build seL4test] | 1 of 1 job failed |

**Job: Set notifications [Build seL4test]**
Build logs

    21-Apr-2021 14:37:33	Build Dev seL4 tests - seL4 PRs: compile seL4test - EXT-axel-h-patch-axel-5-330 - Set notifications [Build seL4test] #1 (SEL4-PHT1614-BUILDSEL4TESTGHSTATUS-1) started building on agent odroid-xu4-1, bamboo version: 7.1.4
    21-Apr-2021 14:37:33	
    21-Apr-2021 14:37:33	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS
    21-Apr-2021 14:37:33	Executing build Dev seL4 tests - seL4 PRs: compile seL4test - EXT-axel-h-patch-axel-5-330 - Set notifications [Build seL4test] #1 (SEL4-PHT1614-BUILDSEL4TESTGHSTATUS-1)
    21-Apr-2021 14:37:33	Preparing artifact 'name.properties' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS/. (location: .)
    21-Apr-2021 14:37:33	Artifact 'name.properties' prepared in 69.85 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS/./name.properties
    21-Apr-2021 14:37:33	Preparing artifact 'sha.properties' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS/. (location: .)
    21-Apr-2021 14:37:33	Artifact 'sha.properties' prepared in 27.69 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS/./sha.properties
    21-Apr-2021 14:37:33	Preparing artifact 'success_Build_seL4test_CLANGARMV6AHWBUILDID' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS/. (location: .)
    21-Apr-2021 14:37:33	Artifact 'success_Build_seL4test_CLANGARMV6AHWBUILDID' prepared in 11.57 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS/./CLANGARMV6AHWBUILDID.Build_seL4test.success
    21-Apr-2021 14:37:33	Preparing artifact 'success_Build_seL4test_CLANGARMV7AHWBUILD1ID' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS/. (location: .)
    21-Apr-2021 14:37:33	Artifact 'success_Build_seL4test_CLANGARMV7AHWBUILD1ID' prepared in 7.477 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS/./CLANGARMV7AHWBUILD1ID.Build_seL4test.success
    21-Apr-2021 14:37:33	Preparing artifact 'success_Build_seL4test_CLANGARMV7AHWBUILD2ID' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS/. (location: .)
    21-Apr-2021 14:37:33	Artifact 'success_Build_seL4test_CLANGARMV7AHWBUILD2ID' prepared in 8.128 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS/./CLANGARMV7AHWBUILD2ID.Build_seL4test.success
    21-Apr-2021 14:37:33	Preparing artifact 'success_Build_seL4test_CLANGARMV8AHWBUILD1ID' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS/. (location: .)
    21-Apr-2021 14:37:33	Artifact 'success_Build_seL4test_CLANGARMV8AHWBUILD1ID' prepared in 13.23 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS/./CLANGARMV8AHWBUILD1ID.Build_seL4test.success
    21-Apr-2021 14:37:33	Preparing artifact 'success_Build_seL4test_CLANGARMV8AHWBUILD2ID' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/174752010/SEL4-PHT1614-BUILDSEL4TESTGHSTATUS/. (location: .)
    21-Apr-2021 14:37:33	Failure in artifact preparation phase during processing of: Subscription for Non required shared artifact: [success_Build_seL4test_CLANGARMV8AHWBUILD2ID], pattern: [*.Build_seL4test.success] anchored at: [.], destination: [.]
    21-Apr-2021 14:37:33	1 error(s) found when performing pre-build actions. 
    21-Apr-2021 14:37:33	Running on server: post build plugin 'NCover Results Collector'
    21-Apr-2021 14:37:33	Running on server: post build plugin 'Build Hanging Detection Configuration'
    21-Apr-2021 14:37:33	Running on server: post build plugin 'Clover Delta Calculator'
    21-Apr-2021 14:37:33	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    21-Apr-2021 14:37:33	All post build plugins have finished
    21-Apr-2021 14:37:33	Generating build results summary...
    21-Apr-2021 14:37:33	Saving build results to disk...
    21-Apr-2021 14:37:33	Store variable context...
    21-Apr-2021 14:37:33	Indexing build results...
    21-Apr-2021 14:37:33	Finished building SEL4-PHT1614-BUILDSEL4TESTGHSTATUS-1.


This is the most I can report on right now, sorry!

**Comment by kent-mcleod** [comment]
@lsf37 , the rebase didn't drop the merge commit... (which wasn't signed-off-by)

**Comment by kent-mcleod** [comment]
Actually disregard my last comment.  The master branch only has 1 commit, but the UI on this PR indicates that 2 commits were merged.

**Pull request merged**
