### PR TITLE
Retain register values when not using IPC buffer

### PR DESCRIPTION
**Pull request by jdub**
- passes the sabre/qemu test suite :-)
- this assumes we want to retain the same number of registers as we
  have input parameters, which on reflection makes no sense at all

### CODE REVIEW

**Comment by jdub** [comment]
Is it okay if we chat about the changes here, rather than clogging up the list with my very specific questions?

In the process of updating this to retain all the real register values, I realise that none of these functions even *get* all of the values, because they're calling `seL4_CallWithMRs` like this:

```c
        output_tag = seL4_CallWithMRs(service, tag,
                &mr0, &mr1, seL4_Null, seL4_Null);
```

The parent function has two input parameters, so it only passes two pointers. We never even see the other two. I'm assuming this is part of the "errors forever lost" problem, because surely the number of error words for a function is unlikely to be related to the number of inputs?

So, the generator should:
- initialise `num_mrs` variables
- pass them *all* to CallWithMRs
- if there's an error, store *all* of them into the IPC buffer

Is that right?

**Comment by AdrianDanis** [comment]
Yep, that all sounds about right to me

**Comment by jdub** [comment]
Bit more to do, but is this approach correct and inoffensive so far?

**Comment by AdrianDanis** [comment]
Looks good so far. I'll probably check the generated functions to be 100% sure though

**Comment by jdub** [comment]
Here are [some examples](https://gist.github.com/jdub/40077cfffcf967a227685bf4880e240f) to save you the git juggling.

**Comment by AdrianDanis** [comment]
So in the case where we are returning a `struct` I think that in the case of an error we should probably be putting MRs into the IPC buffer, and only in the case of success should we put the MRs into the struct.

**Comment by jdub** [comment]
Something like this?

```c
LIBSEL4_INLINE seL4_ARM_Page_GetAddress_t
seL4_ARM_Page_GetAddress(seL4_ARM_Page service)
{
        seL4_ARM_Page_GetAddress_t result;
        seL4_MessageInfo_t tag = seL4_MessageInfo_new(ARMPageGetAddress, 0, 0, 0);
        seL4_MessageInfo_t output_tag;
        seL4_Word mr0 = 0;
        seL4_Word mr1 = 0;
        seL4_Word mr2 = 0;
        seL4_Word mr3 = 0;

        /* Perform the call, passing in-register arguments directly. */
        output_tag = seL4_CallWithMRs(service, tag,
                &mr0, &mr1, &mr2, &mr3);

        result.error = seL4_MessageInfo_get_label(output_tag);

        /* Unmarshal result or retain registers in IPC buffer. */
        if (result.error == seL4_NoError) {
            result.paddr = mr0;
        } else {
                seL4_SetMR(0, mr0);
                seL4_SetMR(1, mr1);
                seL4_SetMR(2, mr2);
                seL4_SetMR(3, mr3);
        }

        return result;
}
```

**Comment by jdub** [comment]
I took a stab at this. How do you feel about [early returns](https://gist.github.com/jdub/d4548690dd82c58b116d3590fa46ed2e)?

**Comment by jdub** [comment]
Looking good on ia32/qemu too.

**Comment by jdub** [comment]
Added *WithMRs basic tests [and posted results](https://gist.github.com/jdub/8e950c3dff0c3941c60a08c0eae279e3). Will have to add something that checks errors, to properly test the *WithMRs path even if the suite is run with `--buffer` generated syscall stubs.

**Comment by AdrianDanis** [comment]
Early return is fine.

This all looks really good. I'm going to run this on some internal projects that use errors (they are what triggered the `--buffer` change to begin with) and if they're good I'll merge it in.

Bit swamped right now though so might not get around to this till monday

**Comment by jdub** [comment]
btw, this depends on #43 and #44 to build.

**Comment by AdrianDanis** [comment]
Ran some tests with this and everything seems to work, so you can neaten the commit history now and we'll be good to go.

**Comment by jdub** [comment]
Squashed!

**Comment by AdrianDanis** [comment]
Awesome. This and all your other changes should appear tonight, unless our regressions are still failing

**Comment by jdub** [comment]
Wow, sweet! Thanks for all your help. This was an enjoyable little achievement. :-)

**Pull request merged**
