### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by berkus**

### CODE REVIEW

**Comment by AdrianDanis** [comment]
Hi @berkus thanks for this and the other issues you raised. Unfortunately I have to point out that we require a [CLA to be signed|http://sel4.systems/Community/Contributing/] for contributions. I hope this is a possibility for you.

**Comment by berkus** [comment]
Sure, I will check it out.

**Comment by berkus** [comment]
CLA signed and sent.

**Comment by AdrianDanis** [comment]
Thanks! Will merge this shortly

**Pull request merged**
