### PR TITLE
trivial: manual: Document SchedContext size_bits meaning

### PR DESCRIPTION
**Pull request by canarysnort01**
**PR Purpose**: Ready to merge.
**Testing perfromed**: Built the manual and visually inspected it.

### CODE REVIEW

**Comment by xurtis** [comment]
The git commit message is too long, can you make it shorter (by 6 or more characters)?

**Comment by branden-data61** [comment]
I would just trim off the word "meaning".

**Comment by canarysnort01** [comment]
Sure thing, done.

**Comment by kent-mcleod** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
