### PR TITLE
fastpath: some risc-v fastpath improvements

### PR DESCRIPTION
**Pull request by oliver-wm**
Inline fastpath functions and call out to them from traps.S.

Signed-off-by: Oliver Scott <Oliver.Scott@data61.csiro.au>

### CODE REVIEW

**Review by xurtis — APPROVED** [review]

**Comment by oliver-wm** [comment]
@lsf37 ok with you from the proof perspective?

**Comment by Xaphiosis** [comment]
Hard to tell at a glance. Obviously the riscv fastpath isn't currently verified.
Is this doing any checks other than "if user invoked reply_recv or call, invoke the relevant fastpath functions, which will fall over to slow path if conditions aren't right"?
It seems `CONFIG_FASTPATH` usage has disappeared.

If I were to go out on a limb, I think verification can handle it. Is this much different what happens on other platforms? I'm missing all the context on why this change is happening, so my questions might be a bit silly.

**Review by yyshen — APPROVED** [review]

**Comment by oliver-wm** [comment]
Ah thanks @Xaphiosis I'll add the CONFIG_FASTPATH usage. It's not doing any other checks and I'm not sure it needs to. They will be handled from slowpath if conditions are not met.

**Comment by lsf37** [comment]
A verification testboard should show up in the checks in the next few minutes.

**Comment by lsf37** [comment]
Testboard passed, good to merge.

**Review by lsf37 — APPROVED** [review]

**Pull request merged**
